// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: builder.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildStatus int32

const (
	BuildStatus_BUILD_STATUS_UNSPECIFIED BuildStatus = 0
	BuildStatus_BUILD_STATUS_PENDING     BuildStatus = 1
	BuildStatus_BUILD_STATUS_BUILDING    BuildStatus = 2
	BuildStatus_BUILD_STATUS_SUCCESS     BuildStatus = 3
	BuildStatus_BUILD_STATUS_FAILED      BuildStatus = 4
)

// Enum value maps for BuildStatus.
var (
	BuildStatus_name = map[int32]string{
		0: "BUILD_STATUS_UNSPECIFIED",
		1: "BUILD_STATUS_PENDING",
		2: "BUILD_STATUS_BUILDING",
		3: "BUILD_STATUS_SUCCESS",
		4: "BUILD_STATUS_FAILED",
	}
	BuildStatus_value = map[string]int32{
		"BUILD_STATUS_UNSPECIFIED": 0,
		"BUILD_STATUS_PENDING":     1,
		"BUILD_STATUS_BUILDING":    2,
		"BUILD_STATUS_SUCCESS":     3,
		"BUILD_STATUS_FAILED":      4,
	}
)

func (x BuildStatus) Enum() *BuildStatus {
	p := new(BuildStatus)
	*p = x
	return p
}

func (x BuildStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_builder_proto_enumTypes[0].Descriptor()
}

func (BuildStatus) Type() protoreflect.EnumType {
	return &file_builder_proto_enumTypes[0]
}

func (x BuildStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildStatus.Descriptor instead.
func (BuildStatus) EnumDescriptor() ([]byte, []int) {
	return file_builder_proto_rawDescGZIP(), []int{0}
}

type BuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	GitUrl        string                 `protobuf:"bytes,2,opt,name=git_url,json=gitUrl,proto3" json:"git_url,omitempty"`
	ImageName     string                 `protobuf:"bytes,3,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	Tag           string                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	GitAuthToken  *string                `protobuf:"bytes,5,opt,name=git_auth_token,json=gitAuthToken,proto3,oneof" json:"git_auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	mi := &file_builder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_builder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_builder_proto_rawDescGZIP(), []int{0}
}

func (x *BuildRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *BuildRequest) GetGitUrl() string {
	if x != nil {
		return x.GitUrl
	}
	return ""
}

func (x *BuildRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *BuildRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *BuildRequest) GetGitAuthToken() string {
	if x != nil && x.GitAuthToken != nil {
		return *x.GitAuthToken
	}
	return ""
}

type BuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BuildId       string                 `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildResponse) Reset() {
	*x = BuildResponse{}
	mi := &file_builder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse) ProtoMessage() {}

func (x *BuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_builder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse.ProtoReflect.Descriptor instead.
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return file_builder_proto_rawDescGZIP(), []int{1}
}

func (x *BuildResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuildResponse) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *BuildResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetBuildStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildStatusRequest) Reset() {
	*x = GetBuildStatusRequest{}
	mi := &file_builder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildStatusRequest) ProtoMessage() {}

func (x *GetBuildStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_builder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildStatusRequest.ProtoReflect.Descriptor instead.
func (*GetBuildStatusRequest) Descriptor() ([]byte, []int) {
	return file_builder_proto_rawDescGZIP(), []int{2}
}

func (x *GetBuildStatusRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

type GetBuildStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BuildId          string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Status           BuildStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=mikrom.builder.v1.BuildStatus" json:"status,omitempty"`
	ImageTag         string                 `protobuf:"bytes,3,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	Message          string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ExposedPort      uint32                 `protobuf:"varint,5,opt,name=exposed_port,json=exposedPort,proto3" json:"exposed_port,omitempty"`
	GitCommitHash    string                 `protobuf:"bytes,6,opt,name=git_commit_hash,json=gitCommitHash,proto3" json:"git_commit_hash,omitempty"`
	GitCommitMessage string                 `protobuf:"bytes,7,opt,name=git_commit_message,json=gitCommitMessage,proto3" json:"git_commit_message,omitempty"`
	GitBranch        string                 `protobuf:"bytes,8,opt,name=git_branch,json=gitBranch,proto3" json:"git_branch,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetBuildStatusResponse) Reset() {
	*x = GetBuildStatusResponse{}
	mi := &file_builder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildStatusResponse) ProtoMessage() {}

func (x *GetBuildStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_builder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildStatusResponse.ProtoReflect.Descriptor instead.
func (*GetBuildStatusResponse) Descriptor() ([]byte, []int) {
	return file_builder_proto_rawDescGZIP(), []int{3}
}

func (x *GetBuildStatusResponse) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *GetBuildStatusResponse) GetStatus() BuildStatus {
	if x != nil {
		return x.Status
	}
	return BuildStatus_BUILD_STATUS_UNSPECIFIED
}

func (x *GetBuildStatusResponse) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

func (x *GetBuildStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetBuildStatusResponse) GetExposedPort() uint32 {
	if x != nil {
		return x.ExposedPort
	}
	return 0
}

func (x *GetBuildStatusResponse) GetGitCommitHash() string {
	if x != nil {
		return x.GitCommitHash
	}
	return ""
}

func (x *GetBuildStatusResponse) GetGitCommitMessage() string {
	if x != nil {
		return x.GitCommitMessage
	}
	return ""
}

func (x *GetBuildStatusResponse) GetGitBranch() string {
	if x != nil {
		return x.GitBranch
	}
	return ""
}

type BuildProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Percent       float32                `protobuf:"fixed32,3,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildProgress) Reset() {
	*x = BuildProgress{}
	mi := &file_builder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildProgress) ProtoMessage() {}

func (x *BuildProgress) ProtoReflect() protoreflect.Message {
	mi := &file_builder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildProgress.ProtoReflect.Descriptor instead.
func (*BuildProgress) Descriptor() ([]byte, []int) {
	return file_builder_proto_rawDescGZIP(), []int{4}
}

func (x *BuildProgress) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *BuildProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BuildProgress) GetPercent() float32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

var File_builder_proto protoreflect.FileDescriptor

const file_builder_proto_rawDesc = "" +
	"\n" +
	"\rbuilder.proto\x12\x11mikrom.builder.v1\"\xad\x01\n" +
	"\fBuildRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x17\n" +
	"\agit_url\x18\x02 \x01(\tR\x06gitUrl\x12\x1d\n" +
	"\n" +
	"image_name\x18\x03 \x01(\tR\timageName\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\x12)\n" +
	"\x0egit_auth_token\x18\x05 \x01(\tH\x00R\fgitAuthToken\x88\x01\x01B\x11\n" +
	"\x0f_git_auth_token\"^\n" +
	"\rBuildResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"2\n" +
	"\x15GetBuildStatusRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\"\xba\x02\n" +
	"\x16GetBuildStatusResponse\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.mikrom.builder.v1.BuildStatusR\x06status\x12\x1b\n" +
	"\timage_tag\x18\x03 \x01(\tR\bimageTag\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12!\n" +
	"\fexposed_port\x18\x05 \x01(\rR\vexposedPort\x12&\n" +
	"\x0fgit_commit_hash\x18\x06 \x01(\tR\rgitCommitHash\x12,\n" +
	"\x12git_commit_message\x18\a \x01(\tR\x10gitCommitMessage\x12\x1d\n" +
	"\n" +
	"git_branch\x18\b \x01(\tR\tgitBranch\"^\n" +
	"\rBuildProgress\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\apercent\x18\x03 \x01(\x02R\apercent*\x93\x01\n" +
	"\vBuildStatus\x12\x1c\n" +
	"\x18BUILD_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14BUILD_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15BUILD_STATUS_BUILDING\x10\x02\x12\x18\n" +
	"\x14BUILD_STATUS_SUCCESS\x10\x03\x12\x17\n" +
	"\x13BUILD_STATUS_FAILED\x10\x042\xc6\x01\n" +
	"\x0eBuilderService\x12M\n" +
	"\bBuildApp\x12\x1f.mikrom.builder.v1.BuildRequest\x1a .mikrom.builder.v1.BuildResponse\x12e\n" +
	"\x0eGetBuildStatus\x12(.mikrom.builder.v1.GetBuildStatusRequest\x1a).mikrom.builder.v1.GetBuildStatusResponseB:Z8github.com/antpard/mikrom/mikrom-router/proto/builder/v1b\x06proto3"

var (
	file_builder_proto_rawDescOnce sync.Once
	file_builder_proto_rawDescData []byte
)

func file_builder_proto_rawDescGZIP() []byte {
	file_builder_proto_rawDescOnce.Do(func() {
		file_builder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_builder_proto_rawDesc), len(file_builder_proto_rawDesc)))
	})
	return file_builder_proto_rawDescData
}

var file_builder_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_builder_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_builder_proto_goTypes = []any{
	(BuildStatus)(0),               // 0: mikrom.builder.v1.BuildStatus
	(*BuildRequest)(nil),           // 1: mikrom.builder.v1.BuildRequest
	(*BuildResponse)(nil),          // 2: mikrom.builder.v1.BuildResponse
	(*GetBuildStatusRequest)(nil),  // 3: mikrom.builder.v1.GetBuildStatusRequest
	(*GetBuildStatusResponse)(nil), // 4: mikrom.builder.v1.GetBuildStatusResponse
	(*BuildProgress)(nil),          // 5: mikrom.builder.v1.BuildProgress
}
var file_builder_proto_depIdxs = []int32{
	0, // 0: mikrom.builder.v1.GetBuildStatusResponse.status:type_name -> mikrom.builder.v1.BuildStatus
	1, // 1: mikrom.builder.v1.BuilderService.BuildApp:input_type -> mikrom.builder.v1.BuildRequest
	3, // 2: mikrom.builder.v1.BuilderService.GetBuildStatus:input_type -> mikrom.builder.v1.GetBuildStatusRequest
	2, // 3: mikrom.builder.v1.BuilderService.BuildApp:output_type -> mikrom.builder.v1.BuildResponse
	4, // 4: mikrom.builder.v1.BuilderService.GetBuildStatus:output_type -> mikrom.builder.v1.GetBuildStatusResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_builder_proto_init() }
func file_builder_proto_init() {
	if File_builder_proto != nil {
		return
	}
	file_builder_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_builder_proto_rawDesc), len(file_builder_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_builder_proto_goTypes,
		DependencyIndexes: file_builder_proto_depIdxs,
		EnumInfos:         file_builder_proto_enumTypes,
		MessageInfos:      file_builder_proto_msgTypes,
	}.Build()
	File_builder_proto = out.File
	file_builder_proto_goTypes = nil
	file_builder_proto_depIdxs = nil
}
