// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VmStatus int32

const (
	VmStatus_VM_STATUS_UNSPECIFIED VmStatus = 0
	VmStatus_VM_STATUS_STARTING    VmStatus = 1
	VmStatus_VM_STATUS_RUNNING     VmStatus = 2
	VmStatus_VM_STATUS_STOPPING    VmStatus = 3
	VmStatus_VM_STATUS_STOPPED     VmStatus = 4
	VmStatus_VM_STATUS_FAILED      VmStatus = 5
	VmStatus_VM_STATUS_PAUSED      VmStatus = 6
)

// Enum value maps for VmStatus.
var (
	VmStatus_name = map[int32]string{
		0: "VM_STATUS_UNSPECIFIED",
		1: "VM_STATUS_STARTING",
		2: "VM_STATUS_RUNNING",
		3: "VM_STATUS_STOPPING",
		4: "VM_STATUS_STOPPED",
		5: "VM_STATUS_FAILED",
		6: "VM_STATUS_PAUSED",
	}
	VmStatus_value = map[string]int32{
		"VM_STATUS_UNSPECIFIED": 0,
		"VM_STATUS_STARTING":    1,
		"VM_STATUS_RUNNING":     2,
		"VM_STATUS_STOPPING":    3,
		"VM_STATUS_STOPPED":     4,
		"VM_STATUS_FAILED":      5,
		"VM_STATUS_PAUSED":      6,
	}
)

func (x VmStatus) Enum() *VmStatus {
	p := new(VmStatus)
	*p = x
	return p
}

func (x VmStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VmStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (VmStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x VmStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VmStatus.Descriptor instead.
func (VmStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type CheckHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthRequest) Reset() {
	*x = CheckHealthRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthRequest) ProtoMessage() {}

func (x *CheckHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckHealthRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *CheckHealthRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type CheckHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsHealthy     bool                   `protobuf:"varint,1,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthResponse) Reset() {
	*x = CheckHealthResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthResponse) ProtoMessage() {}

func (x *CheckHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthResponse.ProtoReflect.Descriptor instead.
func (*CheckHealthResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *CheckHealthResponse) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *CheckHealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AgentCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*AgentCommand_StartVm
	//	*AgentCommand_StopVm
	//	*AgentCommand_PauseVm
	//	*AgentCommand_ResumeVm
	//	*AgentCommand_DeleteVm
	//	*AgentCommand_UpdateFirewall
	Command       isAgentCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommand) Reset() {
	*x = AgentCommand{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommand) ProtoMessage() {}

func (x *AgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommand.ProtoReflect.Descriptor instead.
func (*AgentCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentCommand) GetCommand() isAgentCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *AgentCommand) GetStartVm() *StartVmRequest {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_StartVm); ok {
			return x.StartVm
		}
	}
	return nil
}

func (x *AgentCommand) GetStopVm() *StopVmRequest {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_StopVm); ok {
			return x.StopVm
		}
	}
	return nil
}

func (x *AgentCommand) GetPauseVm() *PauseVmRequest {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_PauseVm); ok {
			return x.PauseVm
		}
	}
	return nil
}

func (x *AgentCommand) GetResumeVm() *ResumeVmRequest {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_ResumeVm); ok {
			return x.ResumeVm
		}
	}
	return nil
}

func (x *AgentCommand) GetDeleteVm() *DeleteVmRequest {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_DeleteVm); ok {
			return x.DeleteVm
		}
	}
	return nil
}

func (x *AgentCommand) GetUpdateFirewall() *UpdateFirewallRequest {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_UpdateFirewall); ok {
			return x.UpdateFirewall
		}
	}
	return nil
}

type isAgentCommand_Command interface {
	isAgentCommand_Command()
}

type AgentCommand_StartVm struct {
	StartVm *StartVmRequest `protobuf:"bytes,1,opt,name=start_vm,json=startVm,proto3,oneof"`
}

type AgentCommand_StopVm struct {
	StopVm *StopVmRequest `protobuf:"bytes,2,opt,name=stop_vm,json=stopVm,proto3,oneof"`
}

type AgentCommand_PauseVm struct {
	PauseVm *PauseVmRequest `protobuf:"bytes,3,opt,name=pause_vm,json=pauseVm,proto3,oneof"`
}

type AgentCommand_ResumeVm struct {
	ResumeVm *ResumeVmRequest `protobuf:"bytes,4,opt,name=resume_vm,json=resumeVm,proto3,oneof"`
}

type AgentCommand_DeleteVm struct {
	DeleteVm *DeleteVmRequest `protobuf:"bytes,5,opt,name=delete_vm,json=deleteVm,proto3,oneof"`
}

type AgentCommand_UpdateFirewall struct {
	UpdateFirewall *UpdateFirewallRequest `protobuf:"bytes,6,opt,name=update_firewall,json=updateFirewall,proto3,oneof"`
}

func (*AgentCommand_StartVm) isAgentCommand_Command() {}

func (*AgentCommand_StopVm) isAgentCommand_Command() {}

func (*AgentCommand_PauseVm) isAgentCommand_Command() {}

func (*AgentCommand_ResumeVm) isAgentCommand_Command() {}

func (*AgentCommand_DeleteVm) isAgentCommand_Command() {}

func (*AgentCommand_UpdateFirewall) isAgentCommand_Command() {}

type FirewallRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	PortStart     int32                  `protobuf:"varint,2,opt,name=port_start,json=portStart,proto3" json:"port_start,omitempty"`
	PortEnd       int32                  `protobuf:"varint,3,opt,name=port_end,json=portEnd,proto3" json:"port_end,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewallRule) Reset() {
	*x = FirewallRule{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallRule) ProtoMessage() {}

func (x *FirewallRule) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallRule.ProtoReflect.Descriptor instead.
func (*FirewallRule) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *FirewallRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *FirewallRule) GetPortStart() int32 {
	if x != nil {
		return x.PortStart
	}
	return 0
}

func (x *FirewallRule) GetPortEnd() int32 {
	if x != nil {
		return x.PortEnd
	}
	return 0
}

func (x *FirewallRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type UpdateFirewallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Rules         []*FirewallRule        `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFirewallRequest) Reset() {
	*x = UpdateFirewallRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFirewallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFirewallRequest) ProtoMessage() {}

func (x *UpdateFirewallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFirewallRequest.ProtoReflect.Descriptor instead.
func (*UpdateFirewallRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateFirewallRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *UpdateFirewallRequest) GetRules() []*FirewallRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type UpdateFirewallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFirewallResponse) Reset() {
	*x = UpdateFirewallResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFirewallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFirewallResponse) ProtoMessage() {}

func (x *UpdateFirewallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFirewallResponse.ProtoReflect.Descriptor instead.
func (*UpdateFirewallResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFirewallResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateFirewallResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AgentCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommandResponse) Reset() {
	*x = AgentCommandResponse{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommandResponse) ProtoMessage() {}

func (x *AgentCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommandResponse.ProtoReflect.Descriptor instead.
func (*AgentCommandResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AgentCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentCommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVmRequest) Reset() {
	*x = DeleteVmRequest{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVmRequest) ProtoMessage() {}

func (x *DeleteVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVmRequest.ProtoReflect.Descriptor instead.
func (*DeleteVmRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type DeleteVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVmResponse) Reset() {
	*x = DeleteVmResponse{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVmResponse) ProtoMessage() {}

func (x *DeleteVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVmResponse.ProtoReflect.Descriptor instead.
func (*DeleteVmResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteVmResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteVmResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PauseVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseVmRequest) Reset() {
	*x = PauseVmRequest{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseVmRequest) ProtoMessage() {}

func (x *PauseVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseVmRequest.ProtoReflect.Descriptor instead.
func (*PauseVmRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *PauseVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type PauseVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseVmResponse) Reset() {
	*x = PauseVmResponse{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseVmResponse) ProtoMessage() {}

func (x *PauseVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseVmResponse.ProtoReflect.Descriptor instead.
func (*PauseVmResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *PauseVmResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PauseVmResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResumeVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeVmRequest) Reset() {
	*x = ResumeVmRequest{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeVmRequest) ProtoMessage() {}

func (x *ResumeVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeVmRequest.ProtoReflect.Descriptor instead.
func (*ResumeVmRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ResumeVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type ResumeVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeVmResponse) Reset() {
	*x = ResumeVmResponse{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeVmResponse) ProtoMessage() {}

func (x *ResumeVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeVmResponse.ProtoReflect.Descriptor instead.
func (*ResumeVmResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ResumeVmResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResumeVmResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *UnregisterRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *UnregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VmMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float32                `protobuf:"fixed32,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsedBytes  uint64                 `protobuf:"varint,2,opt,name=ram_used_bytes,json=ramUsedBytes,proto3" json:"ram_used_bytes,omitempty"`
	Status        VmStatus               `protobuf:"varint,3,opt,name=status,proto3,enum=mikrom.agent.v1.VmStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmMetrics) Reset() {
	*x = VmMetrics{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmMetrics) ProtoMessage() {}

func (x *VmMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmMetrics.ProtoReflect.Descriptor instead.
func (*VmMetrics) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *VmMetrics) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *VmMetrics) GetRamUsedBytes() uint64 {
	if x != nil {
		return x.RamUsedBytes
	}
	return 0
}

func (x *VmMetrics) GetStatus() VmStatus {
	if x != nil {
		return x.Status
	}
	return VmStatus_VM_STATUS_UNSPECIFIED
}

func (x *VmMetrics) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type MetricsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HostId         string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	CpuUsage       float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsedBytes   uint64                 `protobuf:"varint,3,opt,name=ram_used_bytes,json=ramUsedBytes,proto3" json:"ram_used_bytes,omitempty"`
	RamTotalBytes  uint64                 `protobuf:"varint,4,opt,name=ram_total_bytes,json=ramTotalBytes,proto3" json:"ram_total_bytes,omitempty"`
	DiskUsedBytes  uint64                 `protobuf:"varint,5,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes uint64                 `protobuf:"varint,6,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	AppsCount      uint32                 `protobuf:"varint,7,opt,name=apps_count,json=appsCount,proto3" json:"apps_count,omitempty"`
	Timestamp      int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LoadAvg_1      float32                `protobuf:"fixed32,9,opt,name=load_avg_1,json=loadAvg1,proto3" json:"load_avg_1,omitempty"`
	LoadAvg_5      float32                `protobuf:"fixed32,10,opt,name=load_avg_5,json=loadAvg5,proto3" json:"load_avg_5,omitempty"`
	LoadAvg_15     float32                `protobuf:"fixed32,11,opt,name=load_avg_15,json=loadAvg15,proto3" json:"load_avg_15,omitempty"`
	Vms            map[string]*VmMetrics  `protobuf:"bytes,12,rep,name=vms,proto3" json:"vms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *MetricsRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *MetricsRequest) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *MetricsRequest) GetRamUsedBytes() uint64 {
	if x != nil {
		return x.RamUsedBytes
	}
	return 0
}

func (x *MetricsRequest) GetRamTotalBytes() uint64 {
	if x != nil {
		return x.RamTotalBytes
	}
	return 0
}

func (x *MetricsRequest) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *MetricsRequest) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *MetricsRequest) GetAppsCount() uint32 {
	if x != nil {
		return x.AppsCount
	}
	return 0
}

func (x *MetricsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsRequest) GetLoadAvg_1() float32 {
	if x != nil {
		return x.LoadAvg_1
	}
	return 0
}

func (x *MetricsRequest) GetLoadAvg_5() float32 {
	if x != nil {
		return x.LoadAvg_5
	}
	return 0
}

func (x *MetricsRequest) GetLoadAvg_15() float32 {
	if x != nil {
		return x.LoadAvg_15
	}
	return 0
}

func (x *MetricsRequest) GetVms() map[string]*VmMetrics {
	if x != nil {
		return x.Vms
	}
	return nil
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *MetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (x *GetMetricsRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type GetMetricsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HostId         string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	CpuUsage       float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsedBytes   uint64                 `protobuf:"varint,3,opt,name=ram_used_bytes,json=ramUsedBytes,proto3" json:"ram_used_bytes,omitempty"`
	RamTotalBytes  uint64                 `protobuf:"varint,4,opt,name=ram_total_bytes,json=ramTotalBytes,proto3" json:"ram_total_bytes,omitempty"`
	DiskUsedBytes  uint64                 `protobuf:"varint,5,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes uint64                 `protobuf:"varint,6,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	AppsCount      uint32                 `protobuf:"varint,7,opt,name=apps_count,json=appsCount,proto3" json:"apps_count,omitempty"`
	Timestamp      int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LoadAvg_1      float32                `protobuf:"fixed32,9,opt,name=load_avg_1,json=loadAvg1,proto3" json:"load_avg_1,omitempty"`
	LoadAvg_5      float32                `protobuf:"fixed32,10,opt,name=load_avg_5,json=loadAvg5,proto3" json:"load_avg_5,omitempty"`
	LoadAvg_15     float32                `protobuf:"fixed32,11,opt,name=load_avg_15,json=loadAvg15,proto3" json:"load_avg_15,omitempty"`
	Vms            map[string]*VmMetrics  `protobuf:"bytes,12,rep,name=vms,proto3" json:"vms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *GetMetricsResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *GetMetricsResponse) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *GetMetricsResponse) GetRamUsedBytes() uint64 {
	if x != nil {
		return x.RamUsedBytes
	}
	return 0
}

func (x *GetMetricsResponse) GetRamTotalBytes() uint64 {
	if x != nil {
		return x.RamTotalBytes
	}
	return 0
}

func (x *GetMetricsResponse) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *GetMetricsResponse) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *GetMetricsResponse) GetAppsCount() uint32 {
	if x != nil {
		return x.AppsCount
	}
	return 0
}

func (x *GetMetricsResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetMetricsResponse) GetLoadAvg_1() float32 {
	if x != nil {
		return x.LoadAvg_1
	}
	return 0
}

func (x *GetMetricsResponse) GetLoadAvg_5() float32 {
	if x != nil {
		return x.LoadAvg_5
	}
	return 0
}

func (x *GetMetricsResponse) GetLoadAvg_15() float32 {
	if x != nil {
		return x.LoadAvg_15
	}
	return 0
}

func (x *GetMetricsResponse) GetVms() map[string]*VmMetrics {
	if x != nil {
		return x.Vms
	}
	return nil
}

type GetLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsRequest) Reset() {
	*x = GetLogsRequest{}
	mi := &file_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsRequest) ProtoMessage() {}

func (x *GetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{22}
}

func (x *GetLogsRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *GetLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type GetLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsResponse) Reset() {
	*x = GetLogsResponse{}
	mi := &file_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsResponse) ProtoMessage() {}

func (x *GetLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{23}
}

func (x *GetLogsResponse) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *GetLogsResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type StartVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Config        *VmConfig              `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVmRequest) Reset() {
	*x = StartVmRequest{}
	mi := &file_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVmRequest) ProtoMessage() {}

func (x *StartVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVmRequest.ProtoReflect.Descriptor instead.
func (*StartVmRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{24}
}

func (x *StartVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *StartVmRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *StartVmRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *StartVmRequest) GetConfig() *VmConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	SizeMib       uint64                 `protobuf:"varint,2,opt,name=size_mib,json=sizeMib,proto3" json:"size_mib,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{25}
}

func (x *Volume) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *Volume) GetSizeMib() uint64 {
	if x != nil {
		return x.SizeMib
	}
	return 0
}

func (x *Volume) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type VmConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Vcpus           uint32                 `protobuf:"varint,1,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryMib       uint32                 `protobuf:"varint,2,opt,name=memory_mib,json=memoryMib,proto3" json:"memory_mib,omitempty"`
	DiskMib         uint32                 `protobuf:"varint,3,opt,name=disk_mib,json=diskMib,proto3" json:"disk_mib,omitempty"`
	Env             map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Volumes         []*Volume              `protobuf:"bytes,9,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Port            uint32                 `protobuf:"varint,10,opt,name=port,proto3" json:"port,omitempty"`
	HealthCheckPath string                 `protobuf:"bytes,11,opt,name=health_check_path,json=healthCheckPath,proto3" json:"health_check_path,omitempty"`
	Ipv6Address     string                 `protobuf:"bytes,12,opt,name=ipv6_address,json=ipv6Address,proto3" json:"ipv6_address,omitempty"`
	Ipv6Gateway     string                 `protobuf:"bytes,13,opt,name=ipv6_gateway,json=ipv6Gateway,proto3" json:"ipv6_gateway,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VmConfig) Reset() {
	*x = VmConfig{}
	mi := &file_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmConfig) ProtoMessage() {}

func (x *VmConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmConfig.ProtoReflect.Descriptor instead.
func (*VmConfig) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{26}
}

func (x *VmConfig) GetVcpus() uint32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *VmConfig) GetMemoryMib() uint32 {
	if x != nil {
		return x.MemoryMib
	}
	return 0
}

func (x *VmConfig) GetDiskMib() uint32 {
	if x != nil {
		return x.DiskMib
	}
	return 0
}

func (x *VmConfig) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *VmConfig) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *VmConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *VmConfig) GetHealthCheckPath() string {
	if x != nil {
		return x.HealthCheckPath
	}
	return ""
}

func (x *VmConfig) GetIpv6Address() string {
	if x != nil {
		return x.Ipv6Address
	}
	return ""
}

func (x *VmConfig) GetIpv6Gateway() string {
	if x != nil {
		return x.Ipv6Gateway
	}
	return ""
}

type StartVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	VmId          string                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVmResponse) Reset() {
	*x = StartVmResponse{}
	mi := &file_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVmResponse) ProtoMessage() {}

func (x *StartVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVmResponse.ProtoReflect.Descriptor instead.
func (*StartVmResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{27}
}

func (x *StartVmResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartVmResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *StartVmResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVmRequest) Reset() {
	*x = StopVmRequest{}
	mi := &file_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVmRequest) ProtoMessage() {}

func (x *StopVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVmRequest.ProtoReflect.Descriptor instead.
func (*StopVmRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{28}
}

func (x *StopVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type StopVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVmResponse) Reset() {
	*x = StopVmResponse{}
	mi := &file_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVmResponse) ProtoMessage() {}

func (x *StopVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVmResponse.ProtoReflect.Descriptor instead.
func (*StopVmResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{29}
}

func (x *StopVmResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopVmResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetVmStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmStatusRequest) Reset() {
	*x = GetVmStatusRequest{}
	mi := &file_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmStatusRequest) ProtoMessage() {}

func (x *GetVmStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmStatusRequest.ProtoReflect.Descriptor instead.
func (*GetVmStatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{30}
}

func (x *GetVmStatusRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type GetVmStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Status        VmStatus               `protobuf:"varint,2,opt,name=status,proto3,enum=mikrom.agent.v1.VmStatus" json:"status,omitempty"`
	StartedAt     int64                  `protobuf:"varint,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmStatusResponse) Reset() {
	*x = GetVmStatusResponse{}
	mi := &file_agent_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmStatusResponse) ProtoMessage() {}

func (x *GetVmStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmStatusResponse.ProtoReflect.Descriptor instead.
func (*GetVmStatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{31}
}

func (x *GetVmStatusResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *GetVmStatusResponse) GetStatus() VmStatus {
	if x != nil {
		return x.Status
	}
	return VmStatus_VM_STATUS_UNSPECIFIED
}

func (x *GetVmStatusResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *GetVmStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type VmLogPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmLogPayload) Reset() {
	*x = VmLogPayload{}
	mi := &file_agent_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmLogPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmLogPayload) ProtoMessage() {}

func (x *VmLogPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmLogPayload.ProtoReflect.Descriptor instead.
func (*VmLogPayload) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{32}
}

func (x *VmLogPayload) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *VmLogPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x0fmikrom.agent.v1\")\n" +
	"\x12CheckHealthRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"N\n" +
	"\x13CheckHealthResponse\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x01 \x01(\bR\tisHealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa5\x03\n" +
	"\fAgentCommand\x12<\n" +
	"\bstart_vm\x18\x01 \x01(\v2\x1f.mikrom.agent.v1.StartVmRequestH\x00R\astartVm\x129\n" +
	"\astop_vm\x18\x02 \x01(\v2\x1e.mikrom.agent.v1.StopVmRequestH\x00R\x06stopVm\x12<\n" +
	"\bpause_vm\x18\x03 \x01(\v2\x1f.mikrom.agent.v1.PauseVmRequestH\x00R\apauseVm\x12?\n" +
	"\tresume_vm\x18\x04 \x01(\v2 .mikrom.agent.v1.ResumeVmRequestH\x00R\bresumeVm\x12?\n" +
	"\tdelete_vm\x18\x05 \x01(\v2 .mikrom.agent.v1.DeleteVmRequestH\x00R\bdeleteVm\x12Q\n" +
	"\x0fupdate_firewall\x18\x06 \x01(\v2&.mikrom.agent.v1.UpdateFirewallRequestH\x00R\x0eupdateFirewallB\t\n" +
	"\acommand\"|\n" +
	"\fFirewallRule\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"port_start\x18\x02 \x01(\x05R\tportStart\x12\x19\n" +
	"\bport_end\x18\x03 \x01(\x05R\aportEnd\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\"a\n" +
	"\x15UpdateFirewallRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x123\n" +
	"\x05rules\x18\x02 \x03(\v2\x1d.mikrom.agent.v1.FirewallRuleR\x05rules\"L\n" +
	"\x16UpdateFirewallResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"J\n" +
	"\x14AgentCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\x0fDeleteVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"F\n" +
	"\x10DeleteVmResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\x0ePauseVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"E\n" +
	"\x0fPauseVmResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\x0fResumeVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"F\n" +
	"\x10ResumeVmResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostnameJ\x04\b\x03\x10\x04\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x11UnregisterRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\"H\n" +
	"\x12UnregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xac\x01\n" +
	"\tVmMetrics\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x02R\bcpuUsage\x12$\n" +
	"\x0eram_used_bytes\x18\x02 \x01(\x04R\framUsedBytes\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.mikrom.agent.v1.VmStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessageJ\x04\b\x05\x10\x06\"\x8f\x04\n" +
	"\x0eMetricsRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12$\n" +
	"\x0eram_used_bytes\x18\x03 \x01(\x04R\framUsedBytes\x12&\n" +
	"\x0fram_total_bytes\x18\x04 \x01(\x04R\rramTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\x05 \x01(\x04R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\x06 \x01(\x04R\x0ediskTotalBytes\x12\x1d\n" +
	"\n" +
	"apps_count\x18\a \x01(\rR\tappsCount\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\n" +
	"load_avg_1\x18\t \x01(\x02R\bloadAvg1\x12\x1c\n" +
	"\n" +
	"load_avg_5\x18\n" +
	" \x01(\x02R\bloadAvg5\x12\x1e\n" +
	"\vload_avg_15\x18\v \x01(\x02R\tloadAvg15\x12:\n" +
	"\x03vms\x18\f \x03(\v2(.mikrom.agent.v1.MetricsRequest.VmsEntryR\x03vms\x1aR\n" +
	"\bVmsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.mikrom.agent.v1.VmMetricsR\x05value:\x028\x01\"+\n" +
	"\x0fMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x11GetMetricsRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\"\x97\x04\n" +
	"\x12GetMetricsResponse\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12$\n" +
	"\x0eram_used_bytes\x18\x03 \x01(\x04R\framUsedBytes\x12&\n" +
	"\x0fram_total_bytes\x18\x04 \x01(\x04R\rramTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\x05 \x01(\x04R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\x06 \x01(\x04R\x0ediskTotalBytes\x12\x1d\n" +
	"\n" +
	"apps_count\x18\a \x01(\rR\tappsCount\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\n" +
	"load_avg_1\x18\t \x01(\x02R\bloadAvg1\x12\x1c\n" +
	"\n" +
	"load_avg_5\x18\n" +
	" \x01(\x02R\bloadAvg5\x12\x1e\n" +
	"\vload_avg_15\x18\v \x01(\x02R\tloadAvg15\x12>\n" +
	"\x03vms\x18\f \x03(\v2,.mikrom.agent.v1.GetMetricsResponse.VmsEntryR\x03vms\x1aR\n" +
	"\bVmsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.mikrom.agent.v1.VmMetricsR\x05value:\x028\x01\"=\n" +
	"\x0eGetLogsRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\"C\n" +
	"\x0fGetLogsResponse\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\x85\x01\n" +
	"\x0eStartVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x121\n" +
	"\x06config\x18\x04 \x01(\v2\x19.mikrom.agent.v1.VmConfigR\x06config\"]\n" +
	"\x06Volume\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x19\n" +
	"\bsize_mib\x18\x02 \x01(\x04R\asizeMib\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"\x99\x03\n" +
	"\bVmConfig\x12\x14\n" +
	"\x05vcpus\x18\x01 \x01(\rR\x05vcpus\x12\x1d\n" +
	"\n" +
	"memory_mib\x18\x02 \x01(\rR\tmemoryMib\x12\x19\n" +
	"\bdisk_mib\x18\x03 \x01(\rR\adiskMib\x124\n" +
	"\x03env\x18\x04 \x03(\v2\".mikrom.agent.v1.VmConfig.EnvEntryR\x03env\x121\n" +
	"\avolumes\x18\t \x03(\v2\x17.mikrom.agent.v1.VolumeR\avolumes\x12\x12\n" +
	"\x04port\x18\n" +
	" \x01(\rR\x04port\x12*\n" +
	"\x11health_check_path\x18\v \x01(\tR\x0fhealthCheckPath\x12!\n" +
	"\fipv6_address\x18\f \x01(\tR\vipv6Address\x12!\n" +
	"\fipv6_gateway\x18\r \x01(\tR\vipv6Gateway\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\a\x10\bJ\x04\b\b\x10\t\"Z\n" +
	"\x0fStartVmResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\tR\x04vmId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"$\n" +
	"\rStopVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"D\n" +
	"\x0eStopVmResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\")\n" +
	"\x12GetVmStatusRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\xa1\x01\n" +
	"\x13GetVmStatusResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.mikrom.agent.v1.VmStatusR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x03 \x01(\x03R\tstartedAt\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"@\n" +
	"\fVmLogPayload\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp*\xaf\x01\n" +
	"\bVmStatus\x12\x19\n" +
	"\x15VM_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12VM_STATUS_STARTING\x10\x01\x12\x15\n" +
	"\x11VM_STATUS_RUNNING\x10\x02\x12\x16\n" +
	"\x12VM_STATUS_STOPPING\x10\x03\x12\x15\n" +
	"\x11VM_STATUS_STOPPED\x10\x04\x12\x14\n" +
	"\x10VM_STATUS_FAILED\x10\x05\x12\x14\n" +
	"\x10VM_STATUS_PAUSED\x10\x062\xd1\b\n" +
	"\fAgentService\x12O\n" +
	"\bRegister\x12 .mikrom.agent.v1.RegisterRequest\x1a!.mikrom.agent.v1.RegisterResponse\x12U\n" +
	"\n" +
	"Unregister\x12\".mikrom.agent.v1.UnregisterRequest\x1a#.mikrom.agent.v1.UnregisterResponse\x12R\n" +
	"\rReportMetrics\x12\x1f.mikrom.agent.v1.MetricsRequest\x1a .mikrom.agent.v1.MetricsResponse\x12U\n" +
	"\n" +
	"GetMetrics\x12\".mikrom.agent.v1.GetMetricsRequest\x1a#.mikrom.agent.v1.GetMetricsResponse\x12N\n" +
	"\aGetLogs\x12\x1f.mikrom.agent.v1.GetLogsRequest\x1a .mikrom.agent.v1.GetLogsResponse0\x01\x12L\n" +
	"\aStartVm\x12\x1f.mikrom.agent.v1.StartVmRequest\x1a .mikrom.agent.v1.StartVmResponse\x12I\n" +
	"\x06StopVm\x12\x1e.mikrom.agent.v1.StopVmRequest\x1a\x1f.mikrom.agent.v1.StopVmResponse\x12L\n" +
	"\aPauseVm\x12\x1f.mikrom.agent.v1.PauseVmRequest\x1a .mikrom.agent.v1.PauseVmResponse\x12O\n" +
	"\bResumeVm\x12 .mikrom.agent.v1.ResumeVmRequest\x1a!.mikrom.agent.v1.ResumeVmResponse\x12O\n" +
	"\bDeleteVm\x12 .mikrom.agent.v1.DeleteVmRequest\x1a!.mikrom.agent.v1.DeleteVmResponse\x12X\n" +
	"\vGetVmStatus\x12#.mikrom.agent.v1.GetVmStatusRequest\x1a$.mikrom.agent.v1.GetVmStatusResponse\x12X\n" +
	"\vCheckHealth\x12#.mikrom.agent.v1.CheckHealthRequest\x1a$.mikrom.agent.v1.CheckHealthResponse\x12a\n" +
	"\x0eUpdateFirewall\x12&.mikrom.agent.v1.UpdateFirewallRequest\x1a'.mikrom.agent.v1.UpdateFirewallResponseB8Z6github.com/antpard/mikrom/mikrom-router/proto/agent/v1b\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_agent_proto_goTypes = []any{
	(VmStatus)(0),                  // 0: mikrom.agent.v1.VmStatus
	(*CheckHealthRequest)(nil),     // 1: mikrom.agent.v1.CheckHealthRequest
	(*CheckHealthResponse)(nil),    // 2: mikrom.agent.v1.CheckHealthResponse
	(*AgentCommand)(nil),           // 3: mikrom.agent.v1.AgentCommand
	(*FirewallRule)(nil),           // 4: mikrom.agent.v1.FirewallRule
	(*UpdateFirewallRequest)(nil),  // 5: mikrom.agent.v1.UpdateFirewallRequest
	(*UpdateFirewallResponse)(nil), // 6: mikrom.agent.v1.UpdateFirewallResponse
	(*AgentCommandResponse)(nil),   // 7: mikrom.agent.v1.AgentCommandResponse
	(*DeleteVmRequest)(nil),        // 8: mikrom.agent.v1.DeleteVmRequest
	(*DeleteVmResponse)(nil),       // 9: mikrom.agent.v1.DeleteVmResponse
	(*PauseVmRequest)(nil),         // 10: mikrom.agent.v1.PauseVmRequest
	(*PauseVmResponse)(nil),        // 11: mikrom.agent.v1.PauseVmResponse
	(*ResumeVmRequest)(nil),        // 12: mikrom.agent.v1.ResumeVmRequest
	(*ResumeVmResponse)(nil),       // 13: mikrom.agent.v1.ResumeVmResponse
	(*RegisterRequest)(nil),        // 14: mikrom.agent.v1.RegisterRequest
	(*RegisterResponse)(nil),       // 15: mikrom.agent.v1.RegisterResponse
	(*UnregisterRequest)(nil),      // 16: mikrom.agent.v1.UnregisterRequest
	(*UnregisterResponse)(nil),     // 17: mikrom.agent.v1.UnregisterResponse
	(*VmMetrics)(nil),              // 18: mikrom.agent.v1.VmMetrics
	(*MetricsRequest)(nil),         // 19: mikrom.agent.v1.MetricsRequest
	(*MetricsResponse)(nil),        // 20: mikrom.agent.v1.MetricsResponse
	(*GetMetricsRequest)(nil),      // 21: mikrom.agent.v1.GetMetricsRequest
	(*GetMetricsResponse)(nil),     // 22: mikrom.agent.v1.GetMetricsResponse
	(*GetLogsRequest)(nil),         // 23: mikrom.agent.v1.GetLogsRequest
	(*GetLogsResponse)(nil),        // 24: mikrom.agent.v1.GetLogsResponse
	(*StartVmRequest)(nil),         // 25: mikrom.agent.v1.StartVmRequest
	(*Volume)(nil),                 // 26: mikrom.agent.v1.Volume
	(*VmConfig)(nil),               // 27: mikrom.agent.v1.VmConfig
	(*StartVmResponse)(nil),        // 28: mikrom.agent.v1.StartVmResponse
	(*StopVmRequest)(nil),          // 29: mikrom.agent.v1.StopVmRequest
	(*StopVmResponse)(nil),         // 30: mikrom.agent.v1.StopVmResponse
	(*GetVmStatusRequest)(nil),     // 31: mikrom.agent.v1.GetVmStatusRequest
	(*GetVmStatusResponse)(nil),    // 32: mikrom.agent.v1.GetVmStatusResponse
	(*VmLogPayload)(nil),           // 33: mikrom.agent.v1.VmLogPayload
	nil,                            // 34: mikrom.agent.v1.MetricsRequest.VmsEntry
	nil,                            // 35: mikrom.agent.v1.GetMetricsResponse.VmsEntry
	nil,                            // 36: mikrom.agent.v1.VmConfig.EnvEntry
}
var file_agent_proto_depIdxs = []int32{
	25, // 0: mikrom.agent.v1.AgentCommand.start_vm:type_name -> mikrom.agent.v1.StartVmRequest
	29, // 1: mikrom.agent.v1.AgentCommand.stop_vm:type_name -> mikrom.agent.v1.StopVmRequest
	10, // 2: mikrom.agent.v1.AgentCommand.pause_vm:type_name -> mikrom.agent.v1.PauseVmRequest
	12, // 3: mikrom.agent.v1.AgentCommand.resume_vm:type_name -> mikrom.agent.v1.ResumeVmRequest
	8,  // 4: mikrom.agent.v1.AgentCommand.delete_vm:type_name -> mikrom.agent.v1.DeleteVmRequest
	5,  // 5: mikrom.agent.v1.AgentCommand.update_firewall:type_name -> mikrom.agent.v1.UpdateFirewallRequest
	4,  // 6: mikrom.agent.v1.UpdateFirewallRequest.rules:type_name -> mikrom.agent.v1.FirewallRule
	0,  // 7: mikrom.agent.v1.VmMetrics.status:type_name -> mikrom.agent.v1.VmStatus
	34, // 8: mikrom.agent.v1.MetricsRequest.vms:type_name -> mikrom.agent.v1.MetricsRequest.VmsEntry
	35, // 9: mikrom.agent.v1.GetMetricsResponse.vms:type_name -> mikrom.agent.v1.GetMetricsResponse.VmsEntry
	27, // 10: mikrom.agent.v1.StartVmRequest.config:type_name -> mikrom.agent.v1.VmConfig
	36, // 11: mikrom.agent.v1.VmConfig.env:type_name -> mikrom.agent.v1.VmConfig.EnvEntry
	26, // 12: mikrom.agent.v1.VmConfig.volumes:type_name -> mikrom.agent.v1.Volume
	0,  // 13: mikrom.agent.v1.GetVmStatusResponse.status:type_name -> mikrom.agent.v1.VmStatus
	18, // 14: mikrom.agent.v1.MetricsRequest.VmsEntry.value:type_name -> mikrom.agent.v1.VmMetrics
	18, // 15: mikrom.agent.v1.GetMetricsResponse.VmsEntry.value:type_name -> mikrom.agent.v1.VmMetrics
	14, // 16: mikrom.agent.v1.AgentService.Register:input_type -> mikrom.agent.v1.RegisterRequest
	16, // 17: mikrom.agent.v1.AgentService.Unregister:input_type -> mikrom.agent.v1.UnregisterRequest
	19, // 18: mikrom.agent.v1.AgentService.ReportMetrics:input_type -> mikrom.agent.v1.MetricsRequest
	21, // 19: mikrom.agent.v1.AgentService.GetMetrics:input_type -> mikrom.agent.v1.GetMetricsRequest
	23, // 20: mikrom.agent.v1.AgentService.GetLogs:input_type -> mikrom.agent.v1.GetLogsRequest
	25, // 21: mikrom.agent.v1.AgentService.StartVm:input_type -> mikrom.agent.v1.StartVmRequest
	29, // 22: mikrom.agent.v1.AgentService.StopVm:input_type -> mikrom.agent.v1.StopVmRequest
	10, // 23: mikrom.agent.v1.AgentService.PauseVm:input_type -> mikrom.agent.v1.PauseVmRequest
	12, // 24: mikrom.agent.v1.AgentService.ResumeVm:input_type -> mikrom.agent.v1.ResumeVmRequest
	8,  // 25: mikrom.agent.v1.AgentService.DeleteVm:input_type -> mikrom.agent.v1.DeleteVmRequest
	31, // 26: mikrom.agent.v1.AgentService.GetVmStatus:input_type -> mikrom.agent.v1.GetVmStatusRequest
	1,  // 27: mikrom.agent.v1.AgentService.CheckHealth:input_type -> mikrom.agent.v1.CheckHealthRequest
	5,  // 28: mikrom.agent.v1.AgentService.UpdateFirewall:input_type -> mikrom.agent.v1.UpdateFirewallRequest
	15, // 29: mikrom.agent.v1.AgentService.Register:output_type -> mikrom.agent.v1.RegisterResponse
	17, // 30: mikrom.agent.v1.AgentService.Unregister:output_type -> mikrom.agent.v1.UnregisterResponse
	20, // 31: mikrom.agent.v1.AgentService.ReportMetrics:output_type -> mikrom.agent.v1.MetricsResponse
	22, // 32: mikrom.agent.v1.AgentService.GetMetrics:output_type -> mikrom.agent.v1.GetMetricsResponse
	24, // 33: mikrom.agent.v1.AgentService.GetLogs:output_type -> mikrom.agent.v1.GetLogsResponse
	28, // 34: mikrom.agent.v1.AgentService.StartVm:output_type -> mikrom.agent.v1.StartVmResponse
	30, // 35: mikrom.agent.v1.AgentService.StopVm:output_type -> mikrom.agent.v1.StopVmResponse
	11, // 36: mikrom.agent.v1.AgentService.PauseVm:output_type -> mikrom.agent.v1.PauseVmResponse
	13, // 37: mikrom.agent.v1.AgentService.ResumeVm:output_type -> mikrom.agent.v1.ResumeVmResponse
	9,  // 38: mikrom.agent.v1.AgentService.DeleteVm:output_type -> mikrom.agent.v1.DeleteVmResponse
	32, // 39: mikrom.agent.v1.AgentService.GetVmStatus:output_type -> mikrom.agent.v1.GetVmStatusResponse
	2,  // 40: mikrom.agent.v1.AgentService.CheckHealth:output_type -> mikrom.agent.v1.CheckHealthResponse
	6,  // 41: mikrom.agent.v1.AgentService.UpdateFirewall:output_type -> mikrom.agent.v1.UpdateFirewallResponse
	29, // [29:42] is the sub-list for method output_type
	16, // [16:29] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentCommand_StartVm)(nil),
		(*AgentCommand_StopVm)(nil),
		(*AgentCommand_PauseVm)(nil),
		(*AgentCommand_ResumeVm)(nil),
		(*AgentCommand_DeleteVm)(nil),
		(*AgentCommand_UpdateFirewall)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
