global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "mikrom-scheduler"
    static_configs:
      - targets: ["host.docker.internal:5003"]
  - job_name: "mikrom-agent"
    static_configs:
      - targets: ["host.docker.internal:5002"]
  - job_name: "mikrom-router"
    static_configs:
      - targets: ["host.docker.internal:9092"]
