// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: scheduler.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VmStatus int32

const (
	VmStatus_VM_STATUS_UNSPECIFIED VmStatus = 0
	VmStatus_VM_STATUS_STARTING    VmStatus = 1
	VmStatus_VM_STATUS_RUNNING     VmStatus = 2
	VmStatus_VM_STATUS_STOPPING    VmStatus = 3
	VmStatus_VM_STATUS_STOPPED     VmStatus = 4
	VmStatus_VM_STATUS_FAILED      VmStatus = 5
	VmStatus_VM_STATUS_PAUSED      VmStatus = 6
)

// Enum value maps for VmStatus.
var (
	VmStatus_name = map[int32]string{
		0: "VM_STATUS_UNSPECIFIED",
		1: "VM_STATUS_STARTING",
		2: "VM_STATUS_RUNNING",
		3: "VM_STATUS_STOPPING",
		4: "VM_STATUS_STOPPED",
		5: "VM_STATUS_FAILED",
		6: "VM_STATUS_PAUSED",
	}
	VmStatus_value = map[string]int32{
		"VM_STATUS_UNSPECIFIED": 0,
		"VM_STATUS_STARTING":    1,
		"VM_STATUS_RUNNING":     2,
		"VM_STATUS_STOPPING":    3,
		"VM_STATUS_STOPPED":     4,
		"VM_STATUS_FAILED":      5,
		"VM_STATUS_PAUSED":      6,
	}
)

func (x VmStatus) Enum() *VmStatus {
	p := new(VmStatus)
	*p = x
	return p
}

func (x VmStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VmStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduler_proto_enumTypes[0].Descriptor()
}

func (VmStatus) Type() protoreflect.EnumType {
	return &file_scheduler_proto_enumTypes[0]
}

func (x VmStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VmStatus.Descriptor instead.
func (VmStatus) EnumDescriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{0}
}

type DeployStatus int32

const (
	DeployStatus_DEPLOY_STATUS_UNSPECIFIED DeployStatus = 0
	DeployStatus_DEPLOY_STATUS_PENDING     DeployStatus = 1
	DeployStatus_DEPLOY_STATUS_SCHEDULED   DeployStatus = 2
	DeployStatus_DEPLOY_STATUS_RUNNING     DeployStatus = 3
	DeployStatus_DEPLOY_STATUS_FAILED      DeployStatus = 4
	DeployStatus_DEPLOY_STATUS_CANCELLED   DeployStatus = 5
	DeployStatus_DEPLOY_STATUS_PAUSED      DeployStatus = 6
)

// Enum value maps for DeployStatus.
var (
	DeployStatus_name = map[int32]string{
		0: "DEPLOY_STATUS_UNSPECIFIED",
		1: "DEPLOY_STATUS_PENDING",
		2: "DEPLOY_STATUS_SCHEDULED",
		3: "DEPLOY_STATUS_RUNNING",
		4: "DEPLOY_STATUS_FAILED",
		5: "DEPLOY_STATUS_CANCELLED",
		6: "DEPLOY_STATUS_PAUSED",
	}
	DeployStatus_value = map[string]int32{
		"DEPLOY_STATUS_UNSPECIFIED": 0,
		"DEPLOY_STATUS_PENDING":     1,
		"DEPLOY_STATUS_SCHEDULED":   2,
		"DEPLOY_STATUS_RUNNING":     3,
		"DEPLOY_STATUS_FAILED":      4,
		"DEPLOY_STATUS_CANCELLED":   5,
		"DEPLOY_STATUS_PAUSED":      6,
	}
)

func (x DeployStatus) Enum() *DeployStatus {
	p := new(DeployStatus)
	*p = x
	return p
}

func (x DeployStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeployStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduler_proto_enumTypes[1].Descriptor()
}

func (DeployStatus) Type() protoreflect.EnumType {
	return &file_scheduler_proto_enumTypes[1]
}

func (x DeployStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeployStatus.Descriptor instead.
func (DeployStatus) EnumDescriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{1}
}

type NetworkMeshUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMeshUpdate) Reset() {
	*x = NetworkMeshUpdate{}
	mi := &file_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMeshUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMeshUpdate) ProtoMessage() {}

func (x *NetworkMeshUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMeshUpdate.ProtoReflect.Descriptor instead.
func (*NetworkMeshUpdate) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkMeshUpdate) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type FirewallRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	PortStart     int32                  `protobuf:"varint,2,opt,name=port_start,json=portStart,proto3" json:"port_start,omitempty"`
	PortEnd       int32                  `protobuf:"varint,3,opt,name=port_end,json=portEnd,proto3" json:"port_end,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewallRule) Reset() {
	*x = FirewallRule{}
	mi := &file_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallRule) ProtoMessage() {}

func (x *FirewallRule) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallRule.ProtoReflect.Descriptor instead.
func (*FirewallRule) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *FirewallRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *FirewallRule) GetPortStart() int32 {
	if x != nil {
		return x.PortStart
	}
	return 0
}

func (x *FirewallRule) GetPortEnd() int32 {
	if x != nil {
		return x.PortEnd
	}
	return 0
}

func (x *FirewallRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type UpdateSecurityGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rules         []*FirewallRule        `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecurityGroupsRequest) Reset() {
	*x = UpdateSecurityGroupsRequest{}
	mi := &file_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecurityGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecurityGroupsRequest) ProtoMessage() {}

func (x *UpdateSecurityGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecurityGroupsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecurityGroupsRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateSecurityGroupsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *UpdateSecurityGroupsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateSecurityGroupsRequest) GetRules() []*FirewallRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type UpdateSecurityGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecurityGroupsResponse) Reset() {
	*x = UpdateSecurityGroupsResponse{}
	mi := &file_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecurityGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecurityGroupsResponse) ProtoMessage() {}

func (x *UpdateSecurityGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecurityGroupsResponse.ProtoReflect.Descriptor instead.
func (*UpdateSecurityGroupsResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSecurityGroupsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateSecurityGroupsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Peer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HostId          string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	IpAddress       string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	WireguardPubkey string                 `protobuf:"bytes,3,opt,name=wireguard_pubkey,json=wireguardPubkey,proto3" json:"wireguard_pubkey,omitempty"`
	AllowedIps      []string               `protobuf:"bytes,4,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	WireguardPort   int32                  `protobuf:"varint,5,opt,name=wireguard_port,json=wireguardPort,proto3" json:"wireguard_port,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *Peer) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Peer) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Peer) GetWireguardPubkey() string {
	if x != nil {
		return x.WireguardPubkey
	}
	return ""
}

func (x *Peer) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *Peer) GetWireguardPort() int32 {
	if x != nil {
		return x.WireguardPort
	}
	return 0
}

type CheckHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthRequest) Reset() {
	*x = CheckHealthRequest{}
	mi := &file_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthRequest) ProtoMessage() {}

func (x *CheckHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckHealthRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *CheckHealthRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CheckHealthRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsHealthy     bool                   `protobuf:"varint,1,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthResponse) Reset() {
	*x = CheckHealthResponse{}
	mi := &file_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthResponse) ProtoMessage() {}

func (x *CheckHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthResponse.ProtoReflect.Descriptor instead.
func (*CheckHealthResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *CheckHealthResponse) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *CheckHealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WatchAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchAppsRequest) Reset() {
	*x = WatchAppsRequest{}
	mi := &file_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchAppsRequest) ProtoMessage() {}

func (x *WatchAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchAppsRequest.ProtoReflect.Descriptor instead.
func (*WatchAppsRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *WatchAppsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type WatchAppsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *AppInfo               `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchAppsResponse) Reset() {
	*x = WatchAppsResponse{}
	mi := &file_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchAppsResponse) ProtoMessage() {}

func (x *WatchAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchAppsResponse.ProtoReflect.Descriptor instead.
func (*WatchAppsResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *WatchAppsResponse) GetApp() *AppInfo {
	if x != nil {
		return x.App
	}
	return nil
}

type WorkerHeartbeat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HostId          string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Hostname        string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress       string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	BridgeIp        string                 `protobuf:"bytes,5,opt,name=bridge_ip,json=bridgeIp,proto3" json:"bridge_ip,omitempty"`
	Metrics         *ReportMetricsRequest  `protobuf:"bytes,6,opt,name=metrics,proto3" json:"metrics,omitempty"`
	WireguardPubkey string                 `protobuf:"bytes,7,opt,name=wireguard_pubkey,json=wireguardPubkey,proto3" json:"wireguard_pubkey,omitempty"`
	WireguardIp     string                 `protobuf:"bytes,8,opt,name=wireguard_ip,json=wireguardIp,proto3" json:"wireguard_ip,omitempty"`
	WireguardPort   int32                  `protobuf:"varint,9,opt,name=wireguard_port,json=wireguardPort,proto3" json:"wireguard_port,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkerHeartbeat) Reset() {
	*x = WorkerHeartbeat{}
	mi := &file_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHeartbeat) ProtoMessage() {}

func (x *WorkerHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHeartbeat.ProtoReflect.Descriptor instead.
func (*WorkerHeartbeat) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *WorkerHeartbeat) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *WorkerHeartbeat) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *WorkerHeartbeat) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *WorkerHeartbeat) GetBridgeIp() string {
	if x != nil {
		return x.BridgeIp
	}
	return ""
}

func (x *WorkerHeartbeat) GetMetrics() *ReportMetricsRequest {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *WorkerHeartbeat) GetWireguardPubkey() string {
	if x != nil {
		return x.WireguardPubkey
	}
	return ""
}

func (x *WorkerHeartbeat) GetWireguardIp() string {
	if x != nil {
		return x.WireguardIp
	}
	return ""
}

func (x *WorkerHeartbeat) GetWireguardPort() int32 {
	if x != nil {
		return x.WireguardPort
	}
	return 0
}

type RouterHeartbeat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HostId          string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Hostname        string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress       string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	WireguardPubkey string                 `protobuf:"bytes,7,opt,name=wireguard_pubkey,json=wireguardPubkey,proto3" json:"wireguard_pubkey,omitempty"`
	WireguardIp     string                 `protobuf:"bytes,8,opt,name=wireguard_ip,json=wireguardIp,proto3" json:"wireguard_ip,omitempty"`
	WireguardPort   int32                  `protobuf:"varint,9,opt,name=wireguard_port,json=wireguardPort,proto3" json:"wireguard_port,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RouterHeartbeat) Reset() {
	*x = RouterHeartbeat{}
	mi := &file_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterHeartbeat) ProtoMessage() {}

func (x *RouterHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterHeartbeat.ProtoReflect.Descriptor instead.
func (*RouterHeartbeat) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *RouterHeartbeat) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RouterHeartbeat) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RouterHeartbeat) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RouterHeartbeat) GetWireguardPubkey() string {
	if x != nil {
		return x.WireguardPubkey
	}
	return ""
}

func (x *RouterHeartbeat) GetWireguardIp() string {
	if x != nil {
		return x.WireguardIp
	}
	return ""
}

func (x *RouterHeartbeat) GetWireguardPort() int32 {
	if x != nil {
		return x.WireguardPort
	}
	return 0
}

type ListWorkersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersRequest) Reset() {
	*x = ListWorkersRequest{}
	mi := &file_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersRequest) ProtoMessage() {}

func (x *ListWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersRequest.ProtoReflect.Descriptor instead.
func (*ListWorkersRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{11}
}

type ListWorkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*WorkerInfo          `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersResponse) Reset() {
	*x = ListWorkersResponse{}
	mi := &file_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersResponse) ProtoMessage() {}

func (x *ListWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersResponse.ProtoReflect.Descriptor instead.
func (*ListWorkersResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *ListWorkersResponse) GetWorkers() []*WorkerInfo {
	if x != nil {
		return x.Workers
	}
	return nil
}

type WorkerInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HostId          string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Hostname        string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress       string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	BridgeIp        string                 `protobuf:"bytes,5,opt,name=bridge_ip,json=bridgeIp,proto3" json:"bridge_ip,omitempty"`
	LastHeartbeat   int64                  `protobuf:"varint,6,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	WireguardPubkey string                 `protobuf:"bytes,7,opt,name=wireguard_pubkey,json=wireguardPubkey,proto3" json:"wireguard_pubkey,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_scheduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{13}
}

func (x *WorkerInfo) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *WorkerInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *WorkerInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *WorkerInfo) GetBridgeIp() string {
	if x != nil {
		return x.BridgeIp
	}
	return ""
}

func (x *WorkerInfo) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

func (x *WorkerInfo) GetWireguardPubkey() string {
	if x != nil {
		return x.WireguardPubkey
	}
	return ""
}

type PauseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRequest) Reset() {
	*x = PauseRequest{}
	mi := &file_scheduler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRequest) ProtoMessage() {}

func (x *PauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRequest.ProtoReflect.Descriptor instead.
func (*PauseRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{14}
}

func (x *PauseRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PauseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PauseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseResponse) Reset() {
	*x = PauseResponse{}
	mi := &file_scheduler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseResponse) ProtoMessage() {}

func (x *PauseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseResponse.ProtoReflect.Descriptor instead.
func (*PauseResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{15}
}

func (x *PauseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PauseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_scheduler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{16}
}

func (x *ResumeRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ResumeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeResponse) Reset() {
	*x = ResumeResponse{}
	mi := &file_scheduler_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeResponse) ProtoMessage() {}

func (x *ResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeResponse.ProtoReflect.Descriptor instead.
func (*ResumeResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{17}
}

func (x *ResumeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResumeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Follow        bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsRequest) Reset() {
	*x = GetLogsRequest{}
	mi := &file_scheduler_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsRequest) ProtoMessage() {}

func (x *GetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{18}
}

func (x *GetLogsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetLogsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type GetLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsResponse) Reset() {
	*x = GetLogsResponse{}
	mi := &file_scheduler_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsResponse) ProtoMessage() {}

func (x *GetLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{19}
}

func (x *GetLogsResponse) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *GetLogsResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DeleteAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppRequest) Reset() {
	*x = DeleteAppRequest{}
	mi := &file_scheduler_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppRequest) ProtoMessage() {}

func (x *DeleteAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteAppRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *DeleteAppRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppResponse) Reset() {
	*x = DeleteAppResponse{}
	mi := &file_scheduler_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppResponse) ProtoMessage() {}

func (x *DeleteAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppResponse.ProtoReflect.Descriptor instead.
func (*DeleteAppResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteAppResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteAppResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteAllByAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAllByAppRequest) Reset() {
	*x = DeleteAllByAppRequest{}
	mi := &file_scheduler_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAllByAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllByAppRequest) ProtoMessage() {}

func (x *DeleteAllByAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllByAppRequest.ProtoReflect.Descriptor instead.
func (*DeleteAllByAppRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteAllByAppRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *DeleteAllByAppRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteAllByAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAllByAppResponse) Reset() {
	*x = DeleteAllByAppResponse{}
	mi := &file_scheduler_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAllByAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllByAppResponse) ProtoMessage() {}

func (x *DeleteAllByAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllByAppResponse.ProtoReflect.Descriptor instead.
func (*DeleteAllByAppResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteAllByAppResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteAllByAppResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterWorkerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HostId          string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Hostname        string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress       string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	BridgeIp        string                 `protobuf:"bytes,5,opt,name=bridge_ip,json=bridgeIp,proto3" json:"bridge_ip,omitempty"`
	WireguardPubkey string                 `protobuf:"bytes,6,opt,name=wireguard_pubkey,json=wireguardPubkey,proto3" json:"wireguard_pubkey,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_scheduler_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{24}
}

func (x *RegisterWorkerRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterWorkerRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterWorkerRequest) GetBridgeIp() string {
	if x != nil {
		return x.BridgeIp
	}
	return ""
}

func (x *RegisterWorkerRequest) GetWireguardPubkey() string {
	if x != nil {
		return x.WireguardPubkey
	}
	return ""
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_scheduler_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{25}
}

func (x *RegisterWorkerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterWorkerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VmMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float32                `protobuf:"fixed32,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsedBytes  uint64                 `protobuf:"varint,2,opt,name=ram_used_bytes,json=ramUsedBytes,proto3" json:"ram_used_bytes,omitempty"`
	Status        VmStatus               `protobuf:"varint,3,opt,name=status,proto3,enum=mikrom.scheduler.v1.VmStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	TxBytes       uint64                 `protobuf:"varint,6,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxBytes       uint64                 `protobuf:"varint,7,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmMetrics) Reset() {
	*x = VmMetrics{}
	mi := &file_scheduler_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmMetrics) ProtoMessage() {}

func (x *VmMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmMetrics.ProtoReflect.Descriptor instead.
func (*VmMetrics) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{26}
}

func (x *VmMetrics) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *VmMetrics) GetRamUsedBytes() uint64 {
	if x != nil {
		return x.RamUsedBytes
	}
	return 0
}

func (x *VmMetrics) GetStatus() VmStatus {
	if x != nil {
		return x.Status
	}
	return VmStatus_VM_STATUS_UNSPECIFIED
}

func (x *VmMetrics) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *VmMetrics) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *VmMetrics) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *VmMetrics) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

type ReportMetricsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HostId         string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	CpuUsage       float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsedBytes   uint64                 `protobuf:"varint,3,opt,name=ram_used_bytes,json=ramUsedBytes,proto3" json:"ram_used_bytes,omitempty"`
	RamTotalBytes  uint64                 `protobuf:"varint,4,opt,name=ram_total_bytes,json=ramTotalBytes,proto3" json:"ram_total_bytes,omitempty"`
	DiskUsedBytes  uint64                 `protobuf:"varint,5,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes uint64                 `protobuf:"varint,6,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	AppsCount      uint32                 `protobuf:"varint,7,opt,name=apps_count,json=appsCount,proto3" json:"apps_count,omitempty"`
	Timestamp      int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LoadAvg_1      float32                `protobuf:"fixed32,9,opt,name=load_avg_1,json=loadAvg1,proto3" json:"load_avg_1,omitempty"`
	LoadAvg_5      float32                `protobuf:"fixed32,10,opt,name=load_avg_5,json=loadAvg5,proto3" json:"load_avg_5,omitempty"`
	LoadAvg_15     float32                `protobuf:"fixed32,11,opt,name=load_avg_15,json=loadAvg15,proto3" json:"load_avg_15,omitempty"`
	Vms            map[string]*VmMetrics  `protobuf:"bytes,12,rep,name=vms,proto3" json:"vms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportMetricsRequest) Reset() {
	*x = ReportMetricsRequest{}
	mi := &file_scheduler_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMetricsRequest) ProtoMessage() {}

func (x *ReportMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMetricsRequest.ProtoReflect.Descriptor instead.
func (*ReportMetricsRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{27}
}

func (x *ReportMetricsRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ReportMetricsRequest) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ReportMetricsRequest) GetRamUsedBytes() uint64 {
	if x != nil {
		return x.RamUsedBytes
	}
	return 0
}

func (x *ReportMetricsRequest) GetRamTotalBytes() uint64 {
	if x != nil {
		return x.RamTotalBytes
	}
	return 0
}

func (x *ReportMetricsRequest) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *ReportMetricsRequest) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *ReportMetricsRequest) GetAppsCount() uint32 {
	if x != nil {
		return x.AppsCount
	}
	return 0
}

func (x *ReportMetricsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReportMetricsRequest) GetLoadAvg_1() float32 {
	if x != nil {
		return x.LoadAvg_1
	}
	return 0
}

func (x *ReportMetricsRequest) GetLoadAvg_5() float32 {
	if x != nil {
		return x.LoadAvg_5
	}
	return 0
}

func (x *ReportMetricsRequest) GetLoadAvg_15() float32 {
	if x != nil {
		return x.LoadAvg_15
	}
	return 0
}

func (x *ReportMetricsRequest) GetVms() map[string]*VmMetrics {
	if x != nil {
		return x.Vms
	}
	return nil
}

type ReportMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportMetricsResponse) Reset() {
	*x = ReportMetricsResponse{}
	mi := &file_scheduler_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMetricsResponse) ProtoMessage() {}

func (x *ReportMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMetricsResponse.ProtoReflect.Descriptor instead.
func (*ReportMetricsResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{28}
}

func (x *ReportMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Config        *AppConfig             `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,6,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	VpcIpv6Prefix string                 `protobuf:"bytes,7,opt,name=vpc_ipv6_prefix,json=vpcIpv6Prefix,proto3" json:"vpc_ipv6_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_scheduler_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{29}
}

func (x *DeployRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *DeployRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *DeployRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DeployRequest) GetConfig() *AppConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DeployRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeployRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeployRequest) GetVpcIpv6Prefix() string {
	if x != nil {
		return x.VpcIpv6Prefix
	}
	return ""
}

type Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	SizeMib       uint64                 `protobuf:"varint,2,opt,name=size_mib,json=sizeMib,proto3" json:"size_mib,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_scheduler_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{30}
}

func (x *Volume) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *Volume) GetSizeMib() uint64 {
	if x != nil {
		return x.SizeMib
	}
	return 0
}

func (x *Volume) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type AppConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Vcpus           uint32                 `protobuf:"varint,1,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryMib       uint32                 `protobuf:"varint,2,opt,name=memory_mib,json=memoryMib,proto3" json:"memory_mib,omitempty"`
	DiskMib         uint32                 `protobuf:"varint,3,opt,name=disk_mib,json=diskMib,proto3" json:"disk_mib,omitempty"`
	Env             map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IpAddress       string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Gateway         string                 `protobuf:"bytes,6,opt,name=gateway,proto3" json:"gateway,omitempty"`
	MacAddress      string                 `protobuf:"bytes,7,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Volumes         []*Volume              `protobuf:"bytes,8,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Port            uint32                 `protobuf:"varint,9,opt,name=port,proto3" json:"port,omitempty"`
	HealthCheckPath string                 `protobuf:"bytes,10,opt,name=health_check_path,json=healthCheckPath,proto3" json:"health_check_path,omitempty"`
	Ipv6Address     string                 `protobuf:"bytes,11,opt,name=ipv6_address,json=ipv6Address,proto3" json:"ipv6_address,omitempty"`
	Ipv6Gateway     string                 `protobuf:"bytes,12,opt,name=ipv6_gateway,json=ipv6Gateway,proto3" json:"ipv6_gateway,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AppConfig) Reset() {
	*x = AppConfig{}
	mi := &file_scheduler_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppConfig) ProtoMessage() {}

func (x *AppConfig) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppConfig.ProtoReflect.Descriptor instead.
func (*AppConfig) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{31}
}

func (x *AppConfig) GetVcpus() uint32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *AppConfig) GetMemoryMib() uint32 {
	if x != nil {
		return x.MemoryMib
	}
	return 0
}

func (x *AppConfig) GetDiskMib() uint32 {
	if x != nil {
		return x.DiskMib
	}
	return 0
}

func (x *AppConfig) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *AppConfig) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AppConfig) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *AppConfig) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *AppConfig) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *AppConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AppConfig) GetHealthCheckPath() string {
	if x != nil {
		return x.HealthCheckPath
	}
	return ""
}

func (x *AppConfig) GetIpv6Address() string {
	if x != nil {
		return x.Ipv6Address
	}
	return ""
}

func (x *AppConfig) GetIpv6Gateway() string {
	if x != nil {
		return x.Ipv6Gateway
	}
	return ""
}

type DeployResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        DeployStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=mikrom.scheduler.v1.DeployStatus" json:"status,omitempty"`
	HostId        string                 `protobuf:"bytes,3,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	VmId          string                 `protobuf:"bytes,4,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	IpAddress     string                 `protobuf:"bytes,6,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_scheduler_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{32}
}

func (x *DeployResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *DeployResponse) GetStatus() DeployStatus {
	if x != nil {
		return x.Status
	}
	return DeployStatus_DEPLOY_STATUS_UNSPECIFIED
}

func (x *DeployResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *DeployResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *DeployResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeployResponse) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type AppStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppStatusRequest) Reset() {
	*x = AppStatusRequest{}
	mi := &file_scheduler_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppStatusRequest) ProtoMessage() {}

func (x *AppStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppStatusRequest.ProtoReflect.Descriptor instead.
func (*AppStatusRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{33}
}

func (x *AppStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AppStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AppStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        DeployStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=mikrom.scheduler.v1.DeployStatus" json:"status,omitempty"`
	HostId        string                 `protobuf:"bytes,3,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	VmId          string                 `protobuf:"bytes,4,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	ScheduledAt   int64                  `protobuf:"varint,5,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	StartedAt     int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	StoppedAt     int64                  `protobuf:"varint,7,opt,name=stopped_at,json=stoppedAt,proto3" json:"stopped_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CpuUsage      float32                `protobuf:"fixed32,9,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsedBytes  uint64                 `protobuf:"varint,10,opt,name=ram_used_bytes,json=ramUsedBytes,proto3" json:"ram_used_bytes,omitempty"`
	IpAddress     string                 `protobuf:"bytes,11,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Ipv6Address   string                 `protobuf:"bytes,12,opt,name=ipv6_address,json=ipv6Address,proto3" json:"ipv6_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppStatusResponse) Reset() {
	*x = AppStatusResponse{}
	mi := &file_scheduler_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppStatusResponse) ProtoMessage() {}

func (x *AppStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppStatusResponse.ProtoReflect.Descriptor instead.
func (*AppStatusResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{34}
}

func (x *AppStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AppStatusResponse) GetStatus() DeployStatus {
	if x != nil {
		return x.Status
	}
	return DeployStatus_DEPLOY_STATUS_UNSPECIFIED
}

func (x *AppStatusResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *AppStatusResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *AppStatusResponse) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *AppStatusResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *AppStatusResponse) GetStoppedAt() int64 {
	if x != nil {
		return x.StoppedAt
	}
	return 0
}

func (x *AppStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AppStatusResponse) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *AppStatusResponse) GetRamUsedBytes() uint64 {
	if x != nil {
		return x.RamUsedBytes
	}
	return 0
}

func (x *AppStatusResponse) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AppStatusResponse) GetIpv6Address() string {
	if x != nil {
		return x.Ipv6Address
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_scheduler_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{35}
}

func (x *CancelRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_scheduler_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{36}
}

func (x *CancelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        *DeployStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=mikrom.scheduler.v1.DeployStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppsRequest) Reset() {
	*x = ListAppsRequest{}
	mi := &file_scheduler_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsRequest) ProtoMessage() {}

func (x *ListAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsRequest.ProtoReflect.Descriptor instead.
func (*ListAppsRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{37}
}

func (x *ListAppsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListAppsRequest) GetStatus() DeployStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return DeployStatus_DEPLOY_STATUS_UNSPECIFIED
}

type ListAppsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []*AppInfo             `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppsResponse) Reset() {
	*x = ListAppsResponse{}
	mi := &file_scheduler_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsResponse) ProtoMessage() {}

func (x *ListAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsResponse.ProtoReflect.Descriptor instead.
func (*ListAppsResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{38}
}

func (x *ListAppsResponse) GetApps() []*AppInfo {
	if x != nil {
		return x.Apps
	}
	return nil
}

type AppInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Status        DeployStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=mikrom.scheduler.v1.DeployStatus" json:"status,omitempty"`
	HostId        string                 `protobuf:"bytes,6,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	VmId          string                 `protobuf:"bytes,7,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	CpuUsage      float32                `protobuf:"fixed32,8,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsedBytes  uint64                 `protobuf:"varint,9,opt,name=ram_used_bytes,json=ramUsedBytes,proto3" json:"ram_used_bytes,omitempty"`
	UserId        string                 `protobuf:"bytes,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,11,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Ipv6Address   string                 `protobuf:"bytes,12,opt,name=ipv6_address,json=ipv6Address,proto3" json:"ipv6_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppInfo) Reset() {
	*x = AppInfo{}
	mi := &file_scheduler_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfo) ProtoMessage() {}

func (x *AppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfo.ProtoReflect.Descriptor instead.
func (*AppInfo) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{39}
}

func (x *AppInfo) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AppInfo) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AppInfo) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *AppInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *AppInfo) GetStatus() DeployStatus {
	if x != nil {
		return x.Status
	}
	return DeployStatus_DEPLOY_STATUS_UNSPECIFIED
}

func (x *AppInfo) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *AppInfo) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *AppInfo) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *AppInfo) GetRamUsedBytes() uint64 {
	if x != nil {
		return x.RamUsedBytes
	}
	return 0
}

func (x *AppInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AppInfo) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *AppInfo) GetIpv6Address() string {
	if x != nil {
		return x.Ipv6Address
	}
	return ""
}

var File_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x0fscheduler.proto\x12\x13mikrom.scheduler.v1\"D\n" +
	"\x11NetworkMeshUpdate\x12/\n" +
	"\x05peers\x18\x01 \x03(\v2\x19.mikrom.scheduler.v1.PeerR\x05peers\"|\n" +
	"\fFirewallRule\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"port_start\x18\x02 \x01(\x05R\tportStart\x12\x19\n" +
	"\bport_end\x18\x03 \x01(\x05R\aportEnd\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\"\x86\x01\n" +
	"\x1bUpdateSecurityGroupsRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x127\n" +
	"\x05rules\x18\x03 \x03(\v2!.mikrom.scheduler.v1.FirewallRuleR\x05rules\"R\n" +
	"\x1cUpdateSecurityGroupsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb1\x01\n" +
	"\x04Peer\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12)\n" +
	"\x10wireguard_pubkey\x18\x03 \x01(\tR\x0fwireguardPubkey\x12\x1f\n" +
	"\vallowed_ips\x18\x04 \x03(\tR\n" +
	"allowedIps\x12%\n" +
	"\x0ewireguard_port\x18\x05 \x01(\x05R\rwireguardPort\"D\n" +
	"\x12CheckHealthRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"N\n" +
	"\x13CheckHealthResponse\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x01 \x01(\bR\tisHealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"+\n" +
	"\x10WatchAppsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"C\n" +
	"\x11WatchAppsResponse\x12.\n" +
	"\x03app\x18\x01 \x01(\v2\x1c.mikrom.scheduler.v1.AppInfoR\x03app\"\xc2\x02\n" +
	"\x0fWorkerHeartbeat\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1b\n" +
	"\tbridge_ip\x18\x05 \x01(\tR\bbridgeIp\x12C\n" +
	"\ametrics\x18\x06 \x01(\v2).mikrom.scheduler.v1.ReportMetricsRequestR\ametrics\x12)\n" +
	"\x10wireguard_pubkey\x18\a \x01(\tR\x0fwireguardPubkey\x12!\n" +
	"\fwireguard_ip\x18\b \x01(\tR\vwireguardIp\x12%\n" +
	"\x0ewireguard_port\x18\t \x01(\x05R\rwireguardPortJ\x04\b\x04\x10\x05\"\xda\x01\n" +
	"\x0fRouterHeartbeat\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12)\n" +
	"\x10wireguard_pubkey\x18\a \x01(\tR\x0fwireguardPubkey\x12!\n" +
	"\fwireguard_ip\x18\b \x01(\tR\vwireguardIp\x12%\n" +
	"\x0ewireguard_port\x18\t \x01(\x05R\rwireguardPort\"\x14\n" +
	"\x12ListWorkersRequest\"P\n" +
	"\x13ListWorkersResponse\x129\n" +
	"\aworkers\x18\x01 \x03(\v2\x1f.mikrom.scheduler.v1.WorkerInfoR\aworkers\"\xd5\x01\n" +
	"\n" +
	"WorkerInfo\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1b\n" +
	"\tbridge_ip\x18\x05 \x01(\tR\bbridgeIp\x12%\n" +
	"\x0elast_heartbeat\x18\x06 \x01(\x03R\rlastHeartbeat\x12)\n" +
	"\x10wireguard_pubkey\x18\a \x01(\tR\x0fwireguardPubkeyJ\x04\b\x04\x10\x05\">\n" +
	"\fPauseRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"C\n" +
	"\rPauseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"?\n" +
	"\rResumeRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"D\n" +
	"\x0eResumeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"X\n" +
	"\x0eGetLogsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\"C\n" +
	"\x0fGetLogsResponse\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"B\n" +
	"\x10DeleteAppRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"G\n" +
	"\x11DeleteAppResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\x15DeleteAllByAppRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"L\n" +
	"\x16DeleteAllByAppResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb9\x01\n" +
	"\x15RegisterWorkerRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1b\n" +
	"\tbridge_ip\x18\x05 \x01(\tR\bbridgeIp\x12)\n" +
	"\x10wireguard_pubkey\x18\x06 \x01(\tR\x0fwireguardPubkeyJ\x04\b\x04\x10\x05\"L\n" +
	"\x16RegisterWorkerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xff\x01\n" +
	"\tVmMetrics\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x02R\bcpuUsage\x12$\n" +
	"\x0eram_used_bytes\x18\x02 \x01(\x04R\framUsedBytes\x125\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1d.mikrom.scheduler.v1.VmStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12\x19\n" +
	"\btx_bytes\x18\x06 \x01(\x04R\atxBytes\x12\x19\n" +
	"\brx_bytes\x18\a \x01(\x04R\arxBytes\"\xa3\x04\n" +
	"\x14ReportMetricsRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12$\n" +
	"\x0eram_used_bytes\x18\x03 \x01(\x04R\framUsedBytes\x12&\n" +
	"\x0fram_total_bytes\x18\x04 \x01(\x04R\rramTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\x05 \x01(\x04R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\x06 \x01(\x04R\x0ediskTotalBytes\x12\x1d\n" +
	"\n" +
	"apps_count\x18\a \x01(\rR\tappsCount\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\n" +
	"load_avg_1\x18\t \x01(\x02R\bloadAvg1\x12\x1c\n" +
	"\n" +
	"load_avg_5\x18\n" +
	" \x01(\x02R\bloadAvg5\x12\x1e\n" +
	"\vload_avg_15\x18\v \x01(\x02R\tloadAvg15\x12D\n" +
	"\x03vms\x18\f \x03(\v22.mikrom.scheduler.v1.ReportMetricsRequest.VmsEntryR\x03vms\x1aV\n" +
	"\bVmsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.mikrom.scheduler.v1.VmMetricsR\x05value:\x028\x01\"1\n" +
	"\x15ReportMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xf5\x01\n" +
	"\rDeployRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x126\n" +
	"\x06config\x18\x04 \x01(\v2\x1e.mikrom.scheduler.v1.AppConfigR\x06config\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12#\n" +
	"\rdeployment_id\x18\x06 \x01(\tR\fdeploymentId\x12&\n" +
	"\x0fvpc_ipv6_prefix\x18\a \x01(\tR\rvpcIpv6Prefix\"]\n" +
	"\x06Volume\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x19\n" +
	"\bsize_mib\x18\x02 \x01(\x04R\asizeMib\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"\xe5\x03\n" +
	"\tAppConfig\x12\x14\n" +
	"\x05vcpus\x18\x01 \x01(\rR\x05vcpus\x12\x1d\n" +
	"\n" +
	"memory_mib\x18\x02 \x01(\rR\tmemoryMib\x12\x19\n" +
	"\bdisk_mib\x18\x03 \x01(\rR\adiskMib\x129\n" +
	"\x03env\x18\x04 \x03(\v2'.mikrom.scheduler.v1.AppConfig.EnvEntryR\x03env\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12\x18\n" +
	"\agateway\x18\x06 \x01(\tR\agateway\x12\x1f\n" +
	"\vmac_address\x18\a \x01(\tR\n" +
	"macAddress\x125\n" +
	"\avolumes\x18\b \x03(\v2\x1b.mikrom.scheduler.v1.VolumeR\avolumes\x12\x12\n" +
	"\x04port\x18\t \x01(\rR\x04port\x12*\n" +
	"\x11health_check_path\x18\n" +
	" \x01(\tR\x0fhealthCheckPath\x12!\n" +
	"\fipv6_address\x18\v \x01(\tR\vipv6Address\x12!\n" +
	"\fipv6_gateway\x18\f \x01(\tR\vipv6Gateway\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x01\n" +
	"\x0eDeployResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.mikrom.scheduler.v1.DeployStatusR\x06status\x12\x17\n" +
	"\ahost_id\x18\x03 \x01(\tR\x06hostId\x12\x13\n" +
	"\x05vm_id\x18\x04 \x01(\tR\x04vmId\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x06 \x01(\tR\tipAddress\"B\n" +
	"\x10AppStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x9e\x03\n" +
	"\x11AppStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.mikrom.scheduler.v1.DeployStatusR\x06status\x12\x17\n" +
	"\ahost_id\x18\x03 \x01(\tR\x06hostId\x12\x13\n" +
	"\x05vm_id\x18\x04 \x01(\tR\x04vmId\x12!\n" +
	"\fscheduled_at\x18\x05 \x01(\x03R\vscheduledAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12\x1d\n" +
	"\n" +
	"stopped_at\x18\a \x01(\x03R\tstoppedAt\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12\x1b\n" +
	"\tcpu_usage\x18\t \x01(\x02R\bcpuUsage\x12$\n" +
	"\x0eram_used_bytes\x18\n" +
	" \x01(\x04R\framUsedBytes\x12\x1d\n" +
	"\n" +
	"ip_address\x18\v \x01(\tR\tipAddress\x12!\n" +
	"\fipv6_address\x18\f \x01(\tR\vipv6Address\"?\n" +
	"\rCancelRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"D\n" +
	"\x0eCancelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"u\n" +
	"\x0fListAppsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12>\n" +
	"\x06status\x18\x02 \x01(\x0e2!.mikrom.scheduler.v1.DeployStatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"D\n" +
	"\x10ListAppsResponse\x120\n" +
	"\x04apps\x18\x01 \x03(\v2\x1c.mikrom.scheduler.v1.AppInfoR\x04apps\"\xf5\x02\n" +
	"\aAppInfo\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x129\n" +
	"\x06status\x18\x05 \x01(\x0e2!.mikrom.scheduler.v1.DeployStatusR\x06status\x12\x17\n" +
	"\ahost_id\x18\x06 \x01(\tR\x06hostId\x12\x13\n" +
	"\x05vm_id\x18\a \x01(\tR\x04vmId\x12\x1b\n" +
	"\tcpu_usage\x18\b \x01(\x02R\bcpuUsage\x12$\n" +
	"\x0eram_used_bytes\x18\t \x01(\x04R\framUsedBytes\x12\x17\n" +
	"\auser_id\x18\n" +
	" \x01(\tR\x06userId\x12#\n" +
	"\rdeployment_id\x18\v \x01(\tR\fdeploymentId\x12!\n" +
	"\fipv6_address\x18\f \x01(\tR\vipv6Address*\xaf\x01\n" +
	"\bVmStatus\x12\x19\n" +
	"\x15VM_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12VM_STATUS_STARTING\x10\x01\x12\x15\n" +
	"\x11VM_STATUS_RUNNING\x10\x02\x12\x16\n" +
	"\x12VM_STATUS_STOPPING\x10\x03\x12\x15\n" +
	"\x11VM_STATUS_STOPPED\x10\x04\x12\x14\n" +
	"\x10VM_STATUS_FAILED\x10\x05\x12\x14\n" +
	"\x10VM_STATUS_PAUSED\x10\x06*\xd1\x01\n" +
	"\fDeployStatus\x12\x1d\n" +
	"\x19DEPLOY_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DEPLOY_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17DEPLOY_STATUS_SCHEDULED\x10\x02\x12\x19\n" +
	"\x15DEPLOY_STATUS_RUNNING\x10\x03\x12\x18\n" +
	"\x14DEPLOY_STATUS_FAILED\x10\x04\x12\x1b\n" +
	"\x17DEPLOY_STATUS_CANCELLED\x10\x05\x12\x18\n" +
	"\x14DEPLOY_STATUS_PAUSED\x10\x062\xb3\v\n" +
	"\x10SchedulerService\x12i\n" +
	"\x0eRegisterWorker\x12*.mikrom.scheduler.v1.RegisterWorkerRequest\x1a+.mikrom.scheduler.v1.RegisterWorkerResponse\x12f\n" +
	"\rReportMetrics\x12).mikrom.scheduler.v1.ReportMetricsRequest\x1a*.mikrom.scheduler.v1.ReportMetricsResponse\x12T\n" +
	"\tDeployApp\x12\".mikrom.scheduler.v1.DeployRequest\x1a#.mikrom.scheduler.v1.DeployResponse\x12]\n" +
	"\fGetAppStatus\x12%.mikrom.scheduler.v1.AppStatusRequest\x1a&.mikrom.scheduler.v1.AppStatusResponse\x12Y\n" +
	"\n" +
	"GetAppLogs\x12#.mikrom.scheduler.v1.GetLogsRequest\x1a$.mikrom.scheduler.v1.GetLogsResponse0\x01\x12T\n" +
	"\tCancelApp\x12\".mikrom.scheduler.v1.CancelRequest\x1a#.mikrom.scheduler.v1.CancelResponse\x12Q\n" +
	"\bPauseApp\x12!.mikrom.scheduler.v1.PauseRequest\x1a\".mikrom.scheduler.v1.PauseResponse\x12T\n" +
	"\tResumeApp\x12\".mikrom.scheduler.v1.ResumeRequest\x1a#.mikrom.scheduler.v1.ResumeResponse\x12Z\n" +
	"\tDeleteApp\x12%.mikrom.scheduler.v1.DeleteAppRequest\x1a&.mikrom.scheduler.v1.DeleteAppResponse\x12i\n" +
	"\x0eDeleteAllByApp\x12*.mikrom.scheduler.v1.DeleteAllByAppRequest\x1a+.mikrom.scheduler.v1.DeleteAllByAppResponse\x12W\n" +
	"\bListApps\x12$.mikrom.scheduler.v1.ListAppsRequest\x1a%.mikrom.scheduler.v1.ListAppsResponse\x12`\n" +
	"\vListWorkers\x12'.mikrom.scheduler.v1.ListWorkersRequest\x1a(.mikrom.scheduler.v1.ListWorkersResponse\x12\\\n" +
	"\tWatchApps\x12%.mikrom.scheduler.v1.WatchAppsRequest\x1a&.mikrom.scheduler.v1.WatchAppsResponse0\x01\x12`\n" +
	"\vCheckHealth\x12'.mikrom.scheduler.v1.CheckHealthRequest\x1a(.mikrom.scheduler.v1.CheckHealthResponse\x12{\n" +
	"\x14UpdateSecurityGroups\x120.mikrom.scheduler.v1.UpdateSecurityGroupsRequest\x1a1.mikrom.scheduler.v1.UpdateSecurityGroupsResponseB\x15Z\x13mikrom/scheduler/v1b\x06proto3"

var (
	file_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_proto_rawDescData []byte
)

func file_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)))
	})
	return file_scheduler_proto_rawDescData
}

var file_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_scheduler_proto_goTypes = []any{
	(VmStatus)(0),                        // 0: mikrom.scheduler.v1.VmStatus
	(DeployStatus)(0),                    // 1: mikrom.scheduler.v1.DeployStatus
	(*NetworkMeshUpdate)(nil),            // 2: mikrom.scheduler.v1.NetworkMeshUpdate
	(*FirewallRule)(nil),                 // 3: mikrom.scheduler.v1.FirewallRule
	(*UpdateSecurityGroupsRequest)(nil),  // 4: mikrom.scheduler.v1.UpdateSecurityGroupsRequest
	(*UpdateSecurityGroupsResponse)(nil), // 5: mikrom.scheduler.v1.UpdateSecurityGroupsResponse
	(*Peer)(nil),                         // 6: mikrom.scheduler.v1.Peer
	(*CheckHealthRequest)(nil),           // 7: mikrom.scheduler.v1.CheckHealthRequest
	(*CheckHealthResponse)(nil),          // 8: mikrom.scheduler.v1.CheckHealthResponse
	(*WatchAppsRequest)(nil),             // 9: mikrom.scheduler.v1.WatchAppsRequest
	(*WatchAppsResponse)(nil),            // 10: mikrom.scheduler.v1.WatchAppsResponse
	(*WorkerHeartbeat)(nil),              // 11: mikrom.scheduler.v1.WorkerHeartbeat
	(*RouterHeartbeat)(nil),              // 12: mikrom.scheduler.v1.RouterHeartbeat
	(*ListWorkersRequest)(nil),           // 13: mikrom.scheduler.v1.ListWorkersRequest
	(*ListWorkersResponse)(nil),          // 14: mikrom.scheduler.v1.ListWorkersResponse
	(*WorkerInfo)(nil),                   // 15: mikrom.scheduler.v1.WorkerInfo
	(*PauseRequest)(nil),                 // 16: mikrom.scheduler.v1.PauseRequest
	(*PauseResponse)(nil),                // 17: mikrom.scheduler.v1.PauseResponse
	(*ResumeRequest)(nil),                // 18: mikrom.scheduler.v1.ResumeRequest
	(*ResumeResponse)(nil),               // 19: mikrom.scheduler.v1.ResumeResponse
	(*GetLogsRequest)(nil),               // 20: mikrom.scheduler.v1.GetLogsRequest
	(*GetLogsResponse)(nil),              // 21: mikrom.scheduler.v1.GetLogsResponse
	(*DeleteAppRequest)(nil),             // 22: mikrom.scheduler.v1.DeleteAppRequest
	(*DeleteAppResponse)(nil),            // 23: mikrom.scheduler.v1.DeleteAppResponse
	(*DeleteAllByAppRequest)(nil),        // 24: mikrom.scheduler.v1.DeleteAllByAppRequest
	(*DeleteAllByAppResponse)(nil),       // 25: mikrom.scheduler.v1.DeleteAllByAppResponse
	(*RegisterWorkerRequest)(nil),        // 26: mikrom.scheduler.v1.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil),       // 27: mikrom.scheduler.v1.RegisterWorkerResponse
	(*VmMetrics)(nil),                    // 28: mikrom.scheduler.v1.VmMetrics
	(*ReportMetricsRequest)(nil),         // 29: mikrom.scheduler.v1.ReportMetricsRequest
	(*ReportMetricsResponse)(nil),        // 30: mikrom.scheduler.v1.ReportMetricsResponse
	(*DeployRequest)(nil),                // 31: mikrom.scheduler.v1.DeployRequest
	(*Volume)(nil),                       // 32: mikrom.scheduler.v1.Volume
	(*AppConfig)(nil),                    // 33: mikrom.scheduler.v1.AppConfig
	(*DeployResponse)(nil),               // 34: mikrom.scheduler.v1.DeployResponse
	(*AppStatusRequest)(nil),             // 35: mikrom.scheduler.v1.AppStatusRequest
	(*AppStatusResponse)(nil),            // 36: mikrom.scheduler.v1.AppStatusResponse
	(*CancelRequest)(nil),                // 37: mikrom.scheduler.v1.CancelRequest
	(*CancelResponse)(nil),               // 38: mikrom.scheduler.v1.CancelResponse
	(*ListAppsRequest)(nil),              // 39: mikrom.scheduler.v1.ListAppsRequest
	(*ListAppsResponse)(nil),             // 40: mikrom.scheduler.v1.ListAppsResponse
	(*AppInfo)(nil),                      // 41: mikrom.scheduler.v1.AppInfo
	nil,                                  // 42: mikrom.scheduler.v1.ReportMetricsRequest.VmsEntry
	nil,                                  // 43: mikrom.scheduler.v1.AppConfig.EnvEntry
}
var file_scheduler_proto_depIdxs = []int32{
	6,  // 0: mikrom.scheduler.v1.NetworkMeshUpdate.peers:type_name -> mikrom.scheduler.v1.Peer
	3,  // 1: mikrom.scheduler.v1.UpdateSecurityGroupsRequest.rules:type_name -> mikrom.scheduler.v1.FirewallRule
	41, // 2: mikrom.scheduler.v1.WatchAppsResponse.app:type_name -> mikrom.scheduler.v1.AppInfo
	29, // 3: mikrom.scheduler.v1.WorkerHeartbeat.metrics:type_name -> mikrom.scheduler.v1.ReportMetricsRequest
	15, // 4: mikrom.scheduler.v1.ListWorkersResponse.workers:type_name -> mikrom.scheduler.v1.WorkerInfo
	0,  // 5: mikrom.scheduler.v1.VmMetrics.status:type_name -> mikrom.scheduler.v1.VmStatus
	42, // 6: mikrom.scheduler.v1.ReportMetricsRequest.vms:type_name -> mikrom.scheduler.v1.ReportMetricsRequest.VmsEntry
	33, // 7: mikrom.scheduler.v1.DeployRequest.config:type_name -> mikrom.scheduler.v1.AppConfig
	43, // 8: mikrom.scheduler.v1.AppConfig.env:type_name -> mikrom.scheduler.v1.AppConfig.EnvEntry
	32, // 9: mikrom.scheduler.v1.AppConfig.volumes:type_name -> mikrom.scheduler.v1.Volume
	1,  // 10: mikrom.scheduler.v1.DeployResponse.status:type_name -> mikrom.scheduler.v1.DeployStatus
	1,  // 11: mikrom.scheduler.v1.AppStatusResponse.status:type_name -> mikrom.scheduler.v1.DeployStatus
	1,  // 12: mikrom.scheduler.v1.ListAppsRequest.status:type_name -> mikrom.scheduler.v1.DeployStatus
	41, // 13: mikrom.scheduler.v1.ListAppsResponse.apps:type_name -> mikrom.scheduler.v1.AppInfo
	1,  // 14: mikrom.scheduler.v1.AppInfo.status:type_name -> mikrom.scheduler.v1.DeployStatus
	28, // 15: mikrom.scheduler.v1.ReportMetricsRequest.VmsEntry.value:type_name -> mikrom.scheduler.v1.VmMetrics
	26, // 16: mikrom.scheduler.v1.SchedulerService.RegisterWorker:input_type -> mikrom.scheduler.v1.RegisterWorkerRequest
	29, // 17: mikrom.scheduler.v1.SchedulerService.ReportMetrics:input_type -> mikrom.scheduler.v1.ReportMetricsRequest
	31, // 18: mikrom.scheduler.v1.SchedulerService.DeployApp:input_type -> mikrom.scheduler.v1.DeployRequest
	35, // 19: mikrom.scheduler.v1.SchedulerService.GetAppStatus:input_type -> mikrom.scheduler.v1.AppStatusRequest
	20, // 20: mikrom.scheduler.v1.SchedulerService.GetAppLogs:input_type -> mikrom.scheduler.v1.GetLogsRequest
	37, // 21: mikrom.scheduler.v1.SchedulerService.CancelApp:input_type -> mikrom.scheduler.v1.CancelRequest
	16, // 22: mikrom.scheduler.v1.SchedulerService.PauseApp:input_type -> mikrom.scheduler.v1.PauseRequest
	18, // 23: mikrom.scheduler.v1.SchedulerService.ResumeApp:input_type -> mikrom.scheduler.v1.ResumeRequest
	22, // 24: mikrom.scheduler.v1.SchedulerService.DeleteApp:input_type -> mikrom.scheduler.v1.DeleteAppRequest
	24, // 25: mikrom.scheduler.v1.SchedulerService.DeleteAllByApp:input_type -> mikrom.scheduler.v1.DeleteAllByAppRequest
	39, // 26: mikrom.scheduler.v1.SchedulerService.ListApps:input_type -> mikrom.scheduler.v1.ListAppsRequest
	13, // 27: mikrom.scheduler.v1.SchedulerService.ListWorkers:input_type -> mikrom.scheduler.v1.ListWorkersRequest
	9,  // 28: mikrom.scheduler.v1.SchedulerService.WatchApps:input_type -> mikrom.scheduler.v1.WatchAppsRequest
	7,  // 29: mikrom.scheduler.v1.SchedulerService.CheckHealth:input_type -> mikrom.scheduler.v1.CheckHealthRequest
	4,  // 30: mikrom.scheduler.v1.SchedulerService.UpdateSecurityGroups:input_type -> mikrom.scheduler.v1.UpdateSecurityGroupsRequest
	27, // 31: mikrom.scheduler.v1.SchedulerService.RegisterWorker:output_type -> mikrom.scheduler.v1.RegisterWorkerResponse
	30, // 32: mikrom.scheduler.v1.SchedulerService.ReportMetrics:output_type -> mikrom.scheduler.v1.ReportMetricsResponse
	34, // 33: mikrom.scheduler.v1.SchedulerService.DeployApp:output_type -> mikrom.scheduler.v1.DeployResponse
	36, // 34: mikrom.scheduler.v1.SchedulerService.GetAppStatus:output_type -> mikrom.scheduler.v1.AppStatusResponse
	21, // 35: mikrom.scheduler.v1.SchedulerService.GetAppLogs:output_type -> mikrom.scheduler.v1.GetLogsResponse
	38, // 36: mikrom.scheduler.v1.SchedulerService.CancelApp:output_type -> mikrom.scheduler.v1.CancelResponse
	17, // 37: mikrom.scheduler.v1.SchedulerService.PauseApp:output_type -> mikrom.scheduler.v1.PauseResponse
	19, // 38: mikrom.scheduler.v1.SchedulerService.ResumeApp:output_type -> mikrom.scheduler.v1.ResumeResponse
	23, // 39: mikrom.scheduler.v1.SchedulerService.DeleteApp:output_type -> mikrom.scheduler.v1.DeleteAppResponse
	25, // 40: mikrom.scheduler.v1.SchedulerService.DeleteAllByApp:output_type -> mikrom.scheduler.v1.DeleteAllByAppResponse
	40, // 41: mikrom.scheduler.v1.SchedulerService.ListApps:output_type -> mikrom.scheduler.v1.ListAppsResponse
	14, // 42: mikrom.scheduler.v1.SchedulerService.ListWorkers:output_type -> mikrom.scheduler.v1.ListWorkersResponse
	10, // 43: mikrom.scheduler.v1.SchedulerService.WatchApps:output_type -> mikrom.scheduler.v1.WatchAppsResponse
	8,  // 44: mikrom.scheduler.v1.SchedulerService.CheckHealth:output_type -> mikrom.scheduler.v1.CheckHealthResponse
	5,  // 45: mikrom.scheduler.v1.SchedulerService.UpdateSecurityGroups:output_type -> mikrom.scheduler.v1.UpdateSecurityGroupsResponse
	31, // [31:46] is the sub-list for method output_type
	16, // [16:31] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_scheduler_proto_init() }
func file_scheduler_proto_init() {
	if File_scheduler_proto != nil {
		return
	}
	file_scheduler_proto_msgTypes[37].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_proto_depIdxs,
		EnumInfos:         file_scheduler_proto_enumTypes,
		MessageInfos:      file_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_proto = out.File
	file_scheduler_proto_goTypes = nil
	file_scheduler_proto_depIdxs = nil
}
