// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuildRequest {
    #[prost(string, tag = "1")]
    pub app_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub git_url: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub image_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub tag: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuildResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub build_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBuildStatusRequest {
    #[prost(string, tag = "1")]
    pub build_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBuildStatusResponse {
    #[prost(string, tag = "1")]
    pub build_id: ::prost::alloc::string::String,
    #[prost(enumeration = "BuildStatus", tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub image_tag: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub message: ::prost::alloc::string::String,
    #[prost(uint32, tag = "5")]
    pub exposed_port: u32,
    #[prost(string, tag = "6")]
    pub git_commit_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub git_commit_message: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub git_branch: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuildProgress {
    #[prost(string, tag = "1")]
    pub build_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(float, tag = "3")]
    pub percent: f32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BuildStatus {
    Unspecified = 0,
    Pending = 1,
    Building = 2,
    Success = 3,
    Failed = 4,
}
impl BuildStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "BUILD_STATUS_UNSPECIFIED",
            Self::Pending => "BUILD_STATUS_PENDING",
            Self::Building => "BUILD_STATUS_BUILDING",
            Self::Success => "BUILD_STATUS_SUCCESS",
            Self::Failed => "BUILD_STATUS_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BUILD_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "BUILD_STATUS_PENDING" => Some(Self::Pending),
            "BUILD_STATUS_BUILDING" => Some(Self::Building),
            "BUILD_STATUS_SUCCESS" => Some(Self::Success),
            "BUILD_STATUS_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
