// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentCommand {
    #[prost(oneof = "agent_command::Command", tags = "1, 2, 3, 4, 5")]
    pub command: ::core::option::Option<agent_command::Command>,
}
/// Nested message and enum types in `AgentCommand`.
pub mod agent_command {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Command {
        #[prost(message, tag = "1")]
        StartVm(super::StartVmRequest),
        #[prost(message, tag = "2")]
        StopVm(super::StopVmRequest),
        #[prost(message, tag = "3")]
        PauseVm(super::PauseVmRequest),
        #[prost(message, tag = "4")]
        ResumeVm(super::ResumeVmRequest),
        #[prost(message, tag = "5")]
        DeleteVm(super::DeleteVmRequest),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentCommandResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteVmRequest {
    #[prost(string, tag = "1")]
    pub vm_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteVmResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PauseVmRequest {
    #[prost(string, tag = "1")]
    pub vm_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PauseVmResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResumeVmRequest {
    #[prost(string, tag = "1")]
    pub vm_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResumeVmResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterRequest {
    #[prost(string, tag = "1")]
    pub host_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub ip_address: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnregisterRequest {
    #[prost(string, tag = "1")]
    pub host_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnregisterResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VmMetrics {
    #[prost(float, tag = "1")]
    pub cpu_usage: f32,
    #[prost(uint64, tag = "2")]
    pub ram_used_bytes: u64,
    #[prost(enumeration = "VmStatus", tag = "3")]
    pub status: i32,
    #[prost(string, tag = "4")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub ip_address: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetricsRequest {
    #[prost(string, tag = "1")]
    pub host_id: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub cpu_usage: f32,
    #[prost(uint64, tag = "3")]
    pub ram_used_bytes: u64,
    #[prost(uint64, tag = "4")]
    pub ram_total_bytes: u64,
    #[prost(uint64, tag = "5")]
    pub disk_used_bytes: u64,
    #[prost(uint64, tag = "6")]
    pub disk_total_bytes: u64,
    #[prost(uint32, tag = "7")]
    pub apps_count: u32,
    #[prost(int64, tag = "8")]
    pub timestamp: i64,
    #[prost(float, tag = "9")]
    pub load_avg_1: f32,
    #[prost(float, tag = "10")]
    pub load_avg_5: f32,
    #[prost(float, tag = "11")]
    pub load_avg_15: f32,
    #[prost(map = "string, message", tag = "12")]
    pub vms: ::std::collections::HashMap<::prost::alloc::string::String, VmMetrics>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MetricsResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMetricsRequest {
    #[prost(string, tag = "1")]
    pub host_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMetricsResponse {
    #[prost(string, tag = "1")]
    pub host_id: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub cpu_usage: f32,
    #[prost(uint64, tag = "3")]
    pub ram_used_bytes: u64,
    #[prost(uint64, tag = "4")]
    pub ram_total_bytes: u64,
    #[prost(uint64, tag = "5")]
    pub disk_used_bytes: u64,
    #[prost(uint64, tag = "6")]
    pub disk_total_bytes: u64,
    #[prost(uint32, tag = "7")]
    pub apps_count: u32,
    #[prost(int64, tag = "8")]
    pub timestamp: i64,
    #[prost(float, tag = "9")]
    pub load_avg_1: f32,
    #[prost(float, tag = "10")]
    pub load_avg_5: f32,
    #[prost(float, tag = "11")]
    pub load_avg_15: f32,
    #[prost(map = "string, message", tag = "12")]
    pub vms: ::std::collections::HashMap<::prost::alloc::string::String, VmMetrics>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLogsRequest {
    #[prost(string, tag = "1")]
    pub vm_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub follow: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLogsResponse {
    #[prost(string, tag = "1")]
    pub line: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartVmRequest {
    #[prost(string, tag = "1")]
    pub vm_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub app_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub image: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub config: ::core::option::Option<VmConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Volume {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub size_mib: u64,
    #[prost(bool, tag = "3")]
    pub read_only: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VmConfig {
    #[prost(uint32, tag = "1")]
    pub vcpus: u32,
    #[prost(uint32, tag = "2")]
    pub memory_mib: u32,
    #[prost(uint32, tag = "3")]
    pub disk_mib: u32,
    #[prost(map = "string, string", tag = "4")]
    pub env: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "5")]
    pub ip_address: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub gateway: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub mac_address: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub netmask: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "9")]
    pub volumes: ::prost::alloc::vec::Vec<Volume>,
    #[prost(uint32, tag = "10")]
    pub port: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartVmResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub vm_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StopVmRequest {
    #[prost(string, tag = "1")]
    pub vm_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StopVmResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetVmStatusRequest {
    #[prost(string, tag = "1")]
    pub vm_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetVmStatusResponse {
    #[prost(string, tag = "1")]
    pub vm_id: ::prost::alloc::string::String,
    #[prost(enumeration = "VmStatus", tag = "2")]
    pub status: i32,
    #[prost(int64, tag = "3")]
    pub started_at: i64,
    #[prost(string, tag = "4")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VmLogPayload {
    #[prost(string, tag = "1")]
    pub line: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub timestamp: i64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum VmStatus {
    Unspecified = 0,
    Starting = 1,
    Running = 2,
    Stopping = 3,
    Stopped = 4,
    Failed = 5,
    Paused = 6,
}
impl VmStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "VM_STATUS_UNSPECIFIED",
            Self::Starting => "VM_STATUS_STARTING",
            Self::Running => "VM_STATUS_RUNNING",
            Self::Stopping => "VM_STATUS_STOPPING",
            Self::Stopped => "VM_STATUS_STOPPED",
            Self::Failed => "VM_STATUS_FAILED",
            Self::Paused => "VM_STATUS_PAUSED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VM_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "VM_STATUS_STARTING" => Some(Self::Starting),
            "VM_STATUS_RUNNING" => Some(Self::Running),
            "VM_STATUS_STOPPING" => Some(Self::Stopping),
            "VM_STATUS_STOPPED" => Some(Self::Stopped),
            "VM_STATUS_FAILED" => Some(Self::Failed),
            "VM_STATUS_PAUSED" => Some(Self::Paused),
            _ => None,
        }
    }
}
