// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RouterConfigUpdate {
    #[prost(string, tag = "1")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub target_urls: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int64, tag = "3")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RouterConfigAck {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TlsCertificateUpdate {
    #[prost(string, tag = "1")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub cert_chain: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub private_key: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub expires_at: i64,
    #[prost(int64, tag = "5")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AcmeChallengeUpdate {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub key_auth: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub is_delete: bool,
    #[prost(int64, tag = "5")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RouterMetrics {
    #[prost(string, tag = "1")]
    pub router_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub requests_total: u64,
    #[prost(uint64, tag = "3")]
    pub responses_2xx: u64,
    #[prost(uint64, tag = "8")]
    pub responses_3xx: u64,
    #[prost(uint64, tag = "4")]
    pub responses_4xx: u64,
    #[prost(uint64, tag = "5")]
    pub responses_5xx: u64,
    #[prost(double, tag = "6")]
    pub latency_avg_ms: f64,
    #[prost(int64, tag = "7")]
    pub timestamp: i64,
}
