// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchAppsRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchAppsResponse {
    #[prost(message, optional, tag = "1")]
    pub app: ::core::option::Option<AppInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkerHeartbeat {
    #[prost(string, tag = "1")]
    pub host_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub ip_address: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub agent_port: u32,
    #[prost(string, tag = "5")]
    pub bridge_ip: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub metrics: ::core::option::Option<ReportMetricsRequest>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListWorkersRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListWorkersResponse {
    #[prost(message, repeated, tag = "1")]
    pub workers: ::prost::alloc::vec::Vec<WorkerInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkerInfo {
    #[prost(string, tag = "1")]
    pub host_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub ip_address: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub agent_port: u32,
    #[prost(string, tag = "5")]
    pub bridge_ip: ::prost::alloc::string::String,
    #[prost(int64, tag = "6")]
    pub last_heartbeat: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PauseRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PauseResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResumeRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResumeResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLogsRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub follow: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLogsResponse {
    #[prost(string, tag = "1")]
    pub line: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteAppRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteAppResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterWorkerRequest {
    #[prost(string, tag = "1")]
    pub host_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub ip_address: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub agent_port: u32,
    #[prost(string, tag = "5")]
    pub bridge_ip: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterWorkerResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VmMetrics {
    #[prost(float, tag = "1")]
    pub cpu_usage: f32,
    #[prost(uint64, tag = "2")]
    pub ram_used_bytes: u64,
    #[prost(enumeration = "VmStatus", tag = "3")]
    pub status: i32,
    #[prost(string, tag = "4")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub ip_address: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReportMetricsRequest {
    #[prost(string, tag = "1")]
    pub host_id: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub cpu_usage: f32,
    #[prost(uint64, tag = "3")]
    pub ram_used_bytes: u64,
    #[prost(uint64, tag = "4")]
    pub ram_total_bytes: u64,
    #[prost(uint64, tag = "5")]
    pub disk_used_bytes: u64,
    #[prost(uint64, tag = "6")]
    pub disk_total_bytes: u64,
    #[prost(uint32, tag = "7")]
    pub apps_count: u32,
    #[prost(int64, tag = "8")]
    pub timestamp: i64,
    #[prost(float, tag = "9")]
    pub load_avg_1: f32,
    #[prost(float, tag = "10")]
    pub load_avg_5: f32,
    #[prost(float, tag = "11")]
    pub load_avg_15: f32,
    #[prost(map = "string, message", tag = "12")]
    pub vms: ::std::collections::HashMap<::prost::alloc::string::String, VmMetrics>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ReportMetricsResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeployRequest {
    #[prost(string, tag = "1")]
    pub app_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub app_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub image: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub config: ::core::option::Option<AppConfig>,
    #[prost(string, tag = "5")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub deployment_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Volume {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub size_mib: u64,
    #[prost(bool, tag = "3")]
    pub read_only: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppConfig {
    #[prost(uint32, tag = "1")]
    pub vcpus: u32,
    #[prost(uint32, tag = "2")]
    pub memory_mib: u32,
    #[prost(uint32, tag = "3")]
    pub disk_mib: u32,
    #[prost(map = "string, string", tag = "4")]
    pub env: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "5")]
    pub ip_address: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub gateway: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub mac_address: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "8")]
    pub volumes: ::prost::alloc::vec::Vec<Volume>,
    #[prost(uint32, tag = "9")]
    pub port: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeployResponse {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(enumeration = "DeployStatus", tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub host_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub vm_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub ip_address: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppStatusRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppStatusResponse {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(enumeration = "DeployStatus", tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub host_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub vm_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub scheduled_at: i64,
    #[prost(int64, tag = "6")]
    pub started_at: i64,
    #[prost(int64, tag = "7")]
    pub stopped_at: i64,
    #[prost(string, tag = "8")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(float, tag = "9")]
    pub cpu_usage: f32,
    #[prost(uint64, tag = "10")]
    pub ram_used_bytes: u64,
    #[prost(string, tag = "11")]
    pub ip_address: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListAppsRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(enumeration = "DeployStatus", optional, tag = "2")]
    pub status: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListAppsResponse {
    #[prost(message, repeated, tag = "1")]
    pub apps: ::prost::alloc::vec::Vec<AppInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppInfo {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub app_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub app_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub image: ::prost::alloc::string::String,
    #[prost(enumeration = "DeployStatus", tag = "5")]
    pub status: i32,
    #[prost(string, tag = "6")]
    pub host_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub vm_id: ::prost::alloc::string::String,
    #[prost(float, tag = "8")]
    pub cpu_usage: f32,
    #[prost(uint64, tag = "9")]
    pub ram_used_bytes: u64,
    #[prost(string, tag = "10")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub deployment_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum VmStatus {
    Unspecified = 0,
    Starting = 1,
    Running = 2,
    Stopping = 3,
    Stopped = 4,
    Failed = 5,
    Paused = 6,
}
impl VmStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "VM_STATUS_UNSPECIFIED",
            Self::Starting => "VM_STATUS_STARTING",
            Self::Running => "VM_STATUS_RUNNING",
            Self::Stopping => "VM_STATUS_STOPPING",
            Self::Stopped => "VM_STATUS_STOPPED",
            Self::Failed => "VM_STATUS_FAILED",
            Self::Paused => "VM_STATUS_PAUSED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VM_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "VM_STATUS_STARTING" => Some(Self::Starting),
            "VM_STATUS_RUNNING" => Some(Self::Running),
            "VM_STATUS_STOPPING" => Some(Self::Stopping),
            "VM_STATUS_STOPPED" => Some(Self::Stopped),
            "VM_STATUS_FAILED" => Some(Self::Failed),
            "VM_STATUS_PAUSED" => Some(Self::Paused),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DeployStatus {
    Unspecified = 0,
    Pending = 1,
    Scheduled = 2,
    Running = 3,
    Failed = 4,
    Cancelled = 5,
    Paused = 6,
}
impl DeployStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DEPLOY_STATUS_UNSPECIFIED",
            Self::Pending => "DEPLOY_STATUS_PENDING",
            Self::Scheduled => "DEPLOY_STATUS_SCHEDULED",
            Self::Running => "DEPLOY_STATUS_RUNNING",
            Self::Failed => "DEPLOY_STATUS_FAILED",
            Self::Cancelled => "DEPLOY_STATUS_CANCELLED",
            Self::Paused => "DEPLOY_STATUS_PAUSED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DEPLOY_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "DEPLOY_STATUS_PENDING" => Some(Self::Pending),
            "DEPLOY_STATUS_SCHEDULED" => Some(Self::Scheduled),
            "DEPLOY_STATUS_RUNNING" => Some(Self::Running),
            "DEPLOY_STATUS_FAILED" => Some(Self::Failed),
            "DEPLOY_STATUS_CANCELLED" => Some(Self::Cancelled),
            "DEPLOY_STATUS_PAUSED" => Some(Self::Paused),
            _ => None,
        }
    }
}
