// This file is @generated by prost-build.
pub mod mikrom {
    pub mod agent {
        pub mod v1 {
            include!("mikrom.agent.v1.rs");
        }
    }
    pub mod scheduler {
        pub mod v1 {
            include!("mikrom.scheduler.v1.rs");
        }
    }
}
