# Mikrom Router Module Loader
# This file is managed by the mikrom-router-nginx package.

# Load the Mikrom Router Dynamic Module
load_module /usr/lib/nginx/modules/ngx_http_mikrom_router_module.so;

# Allow environment variables to be passed to workers
env DATABASE_URL;
env NATS_URL;
env MASTER_KEY;
